// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package braintreegateway.proxies;

public class Address
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject addressMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "BraintreeGateway.Address";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Company("Company"),
		CountryCodeAlpha2("CountryCodeAlpha2"),
		CountryCodeAlpha3("CountryCodeAlpha3"),
		CountryCodeNumeric("CountryCodeNumeric"),
		CountryName("CountryName"),
		CreatedAt("CreatedAt"),
		CustomerId("CustomerId"),
		ExtendedAddress("ExtendedAddress"),
		FirstName("FirstName"),
		_id("_id"),
		LastName("LastName"),
		Locality("Locality"),
		PostalCode("PostalCode"),
		Region("Region"),
		RecipientName("RecipientName"),
		StreetAddress("StreetAddress"),
		UpdatedAt("UpdatedAt");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Address(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "BraintreeGateway.Address"));
	}

	protected Address(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject addressMendixObject)
	{
		if (addressMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("BraintreeGateway.Address", addressMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a BraintreeGateway.Address");

		this.addressMendixObject = addressMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Address.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static braintreegateway.proxies.Address initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return braintreegateway.proxies.Address.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static braintreegateway.proxies.Address initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		if (com.mendix.core.Core.isSubClassOf("BraintreeGateway.BillingAddress", mendixObject.getType()))
			return braintreegateway.proxies.BillingAddress.initialize(context, mendixObject);

		if (com.mendix.core.Core.isSubClassOf("BraintreeGateway.ShippingAddress", mendixObject.getType()))
			return braintreegateway.proxies.ShippingAddress.initialize(context, mendixObject);

		return new braintreegateway.proxies.Address(context, mendixObject);
	}

	public static braintreegateway.proxies.Address load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return braintreegateway.proxies.Address.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Company
	 */
	public final java.lang.String getCompany()
	{
		return getCompany(getContext());
	}

	/**
	 * @param context
	 * @return value of Company
	 */
	public final java.lang.String getCompany(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Company.toString());
	}

	/**
	 * Set value of Company
	 * @param company
	 */
	public final void setCompany(java.lang.String company)
	{
		setCompany(getContext(), company);
	}

	/**
	 * Set value of Company
	 * @param context
	 * @param company
	 */
	public final void setCompany(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String company)
	{
		getMendixObject().setValue(context, MemberNames.Company.toString(), company);
	}

	/**
	 * @return value of CountryCodeAlpha2
	 */
	public final java.lang.String getCountryCodeAlpha2()
	{
		return getCountryCodeAlpha2(getContext());
	}

	/**
	 * @param context
	 * @return value of CountryCodeAlpha2
	 */
	public final java.lang.String getCountryCodeAlpha2(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CountryCodeAlpha2.toString());
	}

	/**
	 * Set value of CountryCodeAlpha2
	 * @param countrycodealpha2
	 */
	public final void setCountryCodeAlpha2(java.lang.String countrycodealpha2)
	{
		setCountryCodeAlpha2(getContext(), countrycodealpha2);
	}

	/**
	 * Set value of CountryCodeAlpha2
	 * @param context
	 * @param countrycodealpha2
	 */
	public final void setCountryCodeAlpha2(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String countrycodealpha2)
	{
		getMendixObject().setValue(context, MemberNames.CountryCodeAlpha2.toString(), countrycodealpha2);
	}

	/**
	 * @return value of CountryCodeAlpha3
	 */
	public final java.lang.String getCountryCodeAlpha3()
	{
		return getCountryCodeAlpha3(getContext());
	}

	/**
	 * @param context
	 * @return value of CountryCodeAlpha3
	 */
	public final java.lang.String getCountryCodeAlpha3(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CountryCodeAlpha3.toString());
	}

	/**
	 * Set value of CountryCodeAlpha3
	 * @param countrycodealpha3
	 */
	public final void setCountryCodeAlpha3(java.lang.String countrycodealpha3)
	{
		setCountryCodeAlpha3(getContext(), countrycodealpha3);
	}

	/**
	 * Set value of CountryCodeAlpha3
	 * @param context
	 * @param countrycodealpha3
	 */
	public final void setCountryCodeAlpha3(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String countrycodealpha3)
	{
		getMendixObject().setValue(context, MemberNames.CountryCodeAlpha3.toString(), countrycodealpha3);
	}

	/**
	 * @return value of CountryCodeNumeric
	 */
	public final java.lang.String getCountryCodeNumeric()
	{
		return getCountryCodeNumeric(getContext());
	}

	/**
	 * @param context
	 * @return value of CountryCodeNumeric
	 */
	public final java.lang.String getCountryCodeNumeric(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CountryCodeNumeric.toString());
	}

	/**
	 * Set value of CountryCodeNumeric
	 * @param countrycodenumeric
	 */
	public final void setCountryCodeNumeric(java.lang.String countrycodenumeric)
	{
		setCountryCodeNumeric(getContext(), countrycodenumeric);
	}

	/**
	 * Set value of CountryCodeNumeric
	 * @param context
	 * @param countrycodenumeric
	 */
	public final void setCountryCodeNumeric(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String countrycodenumeric)
	{
		getMendixObject().setValue(context, MemberNames.CountryCodeNumeric.toString(), countrycodenumeric);
	}

	/**
	 * @return value of CountryName
	 */
	public final java.lang.String getCountryName()
	{
		return getCountryName(getContext());
	}

	/**
	 * @param context
	 * @return value of CountryName
	 */
	public final java.lang.String getCountryName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CountryName.toString());
	}

	/**
	 * Set value of CountryName
	 * @param countryname
	 */
	public final void setCountryName(java.lang.String countryname)
	{
		setCountryName(getContext(), countryname);
	}

	/**
	 * Set value of CountryName
	 * @param context
	 * @param countryname
	 */
	public final void setCountryName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String countryname)
	{
		getMendixObject().setValue(context, MemberNames.CountryName.toString(), countryname);
	}

	/**
	 * @return value of CreatedAt
	 */
	public final java.lang.Long getCreatedAt()
	{
		return getCreatedAt(getContext());
	}

	/**
	 * @param context
	 * @return value of CreatedAt
	 */
	public final java.lang.Long getCreatedAt(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.CreatedAt.toString());
	}

	/**
	 * Set value of CreatedAt
	 * @param createdat
	 */
	public final void setCreatedAt(java.lang.Long createdat)
	{
		setCreatedAt(getContext(), createdat);
	}

	/**
	 * Set value of CreatedAt
	 * @param context
	 * @param createdat
	 */
	public final void setCreatedAt(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long createdat)
	{
		getMendixObject().setValue(context, MemberNames.CreatedAt.toString(), createdat);
	}

	/**
	 * @return value of CustomerId
	 */
	public final java.lang.String getCustomerId()
	{
		return getCustomerId(getContext());
	}

	/**
	 * @param context
	 * @return value of CustomerId
	 */
	public final java.lang.String getCustomerId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CustomerId.toString());
	}

	/**
	 * Set value of CustomerId
	 * @param customerid
	 */
	public final void setCustomerId(java.lang.String customerid)
	{
		setCustomerId(getContext(), customerid);
	}

	/**
	 * Set value of CustomerId
	 * @param context
	 * @param customerid
	 */
	public final void setCustomerId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String customerid)
	{
		getMendixObject().setValue(context, MemberNames.CustomerId.toString(), customerid);
	}

	/**
	 * @return value of ExtendedAddress
	 */
	public final java.lang.String getExtendedAddress()
	{
		return getExtendedAddress(getContext());
	}

	/**
	 * @param context
	 * @return value of ExtendedAddress
	 */
	public final java.lang.String getExtendedAddress(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ExtendedAddress.toString());
	}

	/**
	 * Set value of ExtendedAddress
	 * @param extendedaddress
	 */
	public final void setExtendedAddress(java.lang.String extendedaddress)
	{
		setExtendedAddress(getContext(), extendedaddress);
	}

	/**
	 * Set value of ExtendedAddress
	 * @param context
	 * @param extendedaddress
	 */
	public final void setExtendedAddress(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String extendedaddress)
	{
		getMendixObject().setValue(context, MemberNames.ExtendedAddress.toString(), extendedaddress);
	}

	/**
	 * @return value of FirstName
	 */
	public final java.lang.String getFirstName()
	{
		return getFirstName(getContext());
	}

	/**
	 * @param context
	 * @return value of FirstName
	 */
	public final java.lang.String getFirstName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FirstName.toString());
	}

	/**
	 * Set value of FirstName
	 * @param firstname
	 */
	public final void setFirstName(java.lang.String firstname)
	{
		setFirstName(getContext(), firstname);
	}

	/**
	 * Set value of FirstName
	 * @param context
	 * @param firstname
	 */
	public final void setFirstName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String firstname)
	{
		getMendixObject().setValue(context, MemberNames.FirstName.toString(), firstname);
	}

	/**
	 * @return value of _id
	 */
	public final java.lang.String get_id()
	{
		return get_id(getContext());
	}

	/**
	 * @param context
	 * @return value of _id
	 */
	public final java.lang.String get_id(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._id.toString());
	}

	/**
	 * Set value of _id
	 * @param _id
	 */
	public final void set_id(java.lang.String _id)
	{
		set_id(getContext(), _id);
	}

	/**
	 * Set value of _id
	 * @param context
	 * @param _id
	 */
	public final void set_id(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _id)
	{
		getMendixObject().setValue(context, MemberNames._id.toString(), _id);
	}

	/**
	 * @return value of LastName
	 */
	public final java.lang.String getLastName()
	{
		return getLastName(getContext());
	}

	/**
	 * @param context
	 * @return value of LastName
	 */
	public final java.lang.String getLastName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.LastName.toString());
	}

	/**
	 * Set value of LastName
	 * @param lastname
	 */
	public final void setLastName(java.lang.String lastname)
	{
		setLastName(getContext(), lastname);
	}

	/**
	 * Set value of LastName
	 * @param context
	 * @param lastname
	 */
	public final void setLastName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String lastname)
	{
		getMendixObject().setValue(context, MemberNames.LastName.toString(), lastname);
	}

	/**
	 * @return value of Locality
	 */
	public final java.lang.String getLocality()
	{
		return getLocality(getContext());
	}

	/**
	 * @param context
	 * @return value of Locality
	 */
	public final java.lang.String getLocality(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Locality.toString());
	}

	/**
	 * Set value of Locality
	 * @param locality
	 */
	public final void setLocality(java.lang.String locality)
	{
		setLocality(getContext(), locality);
	}

	/**
	 * Set value of Locality
	 * @param context
	 * @param locality
	 */
	public final void setLocality(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String locality)
	{
		getMendixObject().setValue(context, MemberNames.Locality.toString(), locality);
	}

	/**
	 * @return value of PostalCode
	 */
	public final java.lang.String getPostalCode()
	{
		return getPostalCode(getContext());
	}

	/**
	 * @param context
	 * @return value of PostalCode
	 */
	public final java.lang.String getPostalCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PostalCode.toString());
	}

	/**
	 * Set value of PostalCode
	 * @param postalcode
	 */
	public final void setPostalCode(java.lang.String postalcode)
	{
		setPostalCode(getContext(), postalcode);
	}

	/**
	 * Set value of PostalCode
	 * @param context
	 * @param postalcode
	 */
	public final void setPostalCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String postalcode)
	{
		getMendixObject().setValue(context, MemberNames.PostalCode.toString(), postalcode);
	}

	/**
	 * @return value of Region
	 */
	public final java.lang.String getRegion()
	{
		return getRegion(getContext());
	}

	/**
	 * @param context
	 * @return value of Region
	 */
	public final java.lang.String getRegion(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Region.toString());
	}

	/**
	 * Set value of Region
	 * @param region
	 */
	public final void setRegion(java.lang.String region)
	{
		setRegion(getContext(), region);
	}

	/**
	 * Set value of Region
	 * @param context
	 * @param region
	 */
	public final void setRegion(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String region)
	{
		getMendixObject().setValue(context, MemberNames.Region.toString(), region);
	}

	/**
	 * @return value of RecipientName
	 */
	public final java.lang.String getRecipientName()
	{
		return getRecipientName(getContext());
	}

	/**
	 * @param context
	 * @return value of RecipientName
	 */
	public final java.lang.String getRecipientName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.RecipientName.toString());
	}

	/**
	 * Set value of RecipientName
	 * @param recipientname
	 */
	public final void setRecipientName(java.lang.String recipientname)
	{
		setRecipientName(getContext(), recipientname);
	}

	/**
	 * Set value of RecipientName
	 * @param context
	 * @param recipientname
	 */
	public final void setRecipientName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String recipientname)
	{
		getMendixObject().setValue(context, MemberNames.RecipientName.toString(), recipientname);
	}

	/**
	 * @return value of StreetAddress
	 */
	public final java.lang.String getStreetAddress()
	{
		return getStreetAddress(getContext());
	}

	/**
	 * @param context
	 * @return value of StreetAddress
	 */
	public final java.lang.String getStreetAddress(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.StreetAddress.toString());
	}

	/**
	 * Set value of StreetAddress
	 * @param streetaddress
	 */
	public final void setStreetAddress(java.lang.String streetaddress)
	{
		setStreetAddress(getContext(), streetaddress);
	}

	/**
	 * Set value of StreetAddress
	 * @param context
	 * @param streetaddress
	 */
	public final void setStreetAddress(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String streetaddress)
	{
		getMendixObject().setValue(context, MemberNames.StreetAddress.toString(), streetaddress);
	}

	/**
	 * @return value of UpdatedAt
	 */
	public final java.lang.Long getUpdatedAt()
	{
		return getUpdatedAt(getContext());
	}

	/**
	 * @param context
	 * @return value of UpdatedAt
	 */
	public final java.lang.Long getUpdatedAt(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.UpdatedAt.toString());
	}

	/**
	 * Set value of UpdatedAt
	 * @param updatedat
	 */
	public final void setUpdatedAt(java.lang.Long updatedat)
	{
		setUpdatedAt(getContext(), updatedat);
	}

	/**
	 * Set value of UpdatedAt
	 * @param context
	 * @param updatedat
	 */
	public final void setUpdatedAt(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long updatedat)
	{
		getMendixObject().setValue(context, MemberNames.UpdatedAt.toString(), updatedat);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return addressMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final braintreegateway.proxies.Address that = (braintreegateway.proxies.Address) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "BraintreeGateway.Address";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
