// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package braintreegateway.proxies;

public class AndroidPayDetails extends braintreegateway.proxies.PaymentType
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "BraintreeGateway.AndroidPayDetails";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		SourceCardType("SourceCardType"),
		SourceCardLast4("SourceCardLast4"),
		SourceDescription("SourceDescription"),
		VirtualCardType("VirtualCardType"),
		VirtualCardLast4("VirtualCardLast4"),
		GoogleTransactionId("GoogleTransactionId"),
		GlobalId("GlobalId"),
		NetworkTokenized("NetworkTokenized"),
		CardType("CardType"),
		ExpirationMonth("ExpirationMonth"),
		ExpirationYear("ExpirationYear"),
		Debit("Debit"),
		IssuingBank("IssuingBank"),
		Bin("Bin"),
		Prepaid("Prepaid"),
		Last4("Last4"),
		Payroll("Payroll"),
		CountryOfIssuance("CountryOfIssuance"),
		Healthcare("Healthcare"),
		Commercial("Commercial"),
		DurbinRegulated("DurbinRegulated"),
		ProductId("ProductId"),
		Token("Token"),
		ImageUrl("ImageUrl"),
		AndroidPayDetails_Transaction("BraintreeGateway.AndroidPayDetails_Transaction");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public AndroidPayDetails(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "BraintreeGateway.AndroidPayDetails"));
	}

	protected AndroidPayDetails(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject androidPayDetailsMendixObject)
	{
		super(context, androidPayDetailsMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("BraintreeGateway.AndroidPayDetails", androidPayDetailsMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a BraintreeGateway.AndroidPayDetails");
	}

	/**
	 * @deprecated Use 'AndroidPayDetails.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static braintreegateway.proxies.AndroidPayDetails initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return braintreegateway.proxies.AndroidPayDetails.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static braintreegateway.proxies.AndroidPayDetails initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new braintreegateway.proxies.AndroidPayDetails(context, mendixObject);
	}

	public static braintreegateway.proxies.AndroidPayDetails load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return braintreegateway.proxies.AndroidPayDetails.initialize(context, mendixObject);
	}

	/**
	 * @return value of SourceCardType
	 */
	public final java.lang.String getSourceCardType()
	{
		return getSourceCardType(getContext());
	}

	/**
	 * @param context
	 * @return value of SourceCardType
	 */
	public final java.lang.String getSourceCardType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SourceCardType.toString());
	}

	/**
	 * Set value of SourceCardType
	 * @param sourcecardtype
	 */
	public final void setSourceCardType(java.lang.String sourcecardtype)
	{
		setSourceCardType(getContext(), sourcecardtype);
	}

	/**
	 * Set value of SourceCardType
	 * @param context
	 * @param sourcecardtype
	 */
	public final void setSourceCardType(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String sourcecardtype)
	{
		getMendixObject().setValue(context, MemberNames.SourceCardType.toString(), sourcecardtype);
	}

	/**
	 * @return value of SourceCardLast4
	 */
	public final java.lang.String getSourceCardLast4()
	{
		return getSourceCardLast4(getContext());
	}

	/**
	 * @param context
	 * @return value of SourceCardLast4
	 */
	public final java.lang.String getSourceCardLast4(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SourceCardLast4.toString());
	}

	/**
	 * Set value of SourceCardLast4
	 * @param sourcecardlast4
	 */
	public final void setSourceCardLast4(java.lang.String sourcecardlast4)
	{
		setSourceCardLast4(getContext(), sourcecardlast4);
	}

	/**
	 * Set value of SourceCardLast4
	 * @param context
	 * @param sourcecardlast4
	 */
	public final void setSourceCardLast4(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String sourcecardlast4)
	{
		getMendixObject().setValue(context, MemberNames.SourceCardLast4.toString(), sourcecardlast4);
	}

	/**
	 * @return value of SourceDescription
	 */
	public final java.lang.String getSourceDescription()
	{
		return getSourceDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of SourceDescription
	 */
	public final java.lang.String getSourceDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SourceDescription.toString());
	}

	/**
	 * Set value of SourceDescription
	 * @param sourcedescription
	 */
	public final void setSourceDescription(java.lang.String sourcedescription)
	{
		setSourceDescription(getContext(), sourcedescription);
	}

	/**
	 * Set value of SourceDescription
	 * @param context
	 * @param sourcedescription
	 */
	public final void setSourceDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String sourcedescription)
	{
		getMendixObject().setValue(context, MemberNames.SourceDescription.toString(), sourcedescription);
	}

	/**
	 * @return value of VirtualCardType
	 */
	public final java.lang.String getVirtualCardType()
	{
		return getVirtualCardType(getContext());
	}

	/**
	 * @param context
	 * @return value of VirtualCardType
	 */
	public final java.lang.String getVirtualCardType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.VirtualCardType.toString());
	}

	/**
	 * Set value of VirtualCardType
	 * @param virtualcardtype
	 */
	public final void setVirtualCardType(java.lang.String virtualcardtype)
	{
		setVirtualCardType(getContext(), virtualcardtype);
	}

	/**
	 * Set value of VirtualCardType
	 * @param context
	 * @param virtualcardtype
	 */
	public final void setVirtualCardType(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String virtualcardtype)
	{
		getMendixObject().setValue(context, MemberNames.VirtualCardType.toString(), virtualcardtype);
	}

	/**
	 * @return value of VirtualCardLast4
	 */
	public final java.lang.String getVirtualCardLast4()
	{
		return getVirtualCardLast4(getContext());
	}

	/**
	 * @param context
	 * @return value of VirtualCardLast4
	 */
	public final java.lang.String getVirtualCardLast4(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.VirtualCardLast4.toString());
	}

	/**
	 * Set value of VirtualCardLast4
	 * @param virtualcardlast4
	 */
	public final void setVirtualCardLast4(java.lang.String virtualcardlast4)
	{
		setVirtualCardLast4(getContext(), virtualcardlast4);
	}

	/**
	 * Set value of VirtualCardLast4
	 * @param context
	 * @param virtualcardlast4
	 */
	public final void setVirtualCardLast4(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String virtualcardlast4)
	{
		getMendixObject().setValue(context, MemberNames.VirtualCardLast4.toString(), virtualcardlast4);
	}

	/**
	 * @return value of GoogleTransactionId
	 */
	public final java.lang.String getGoogleTransactionId()
	{
		return getGoogleTransactionId(getContext());
	}

	/**
	 * @param context
	 * @return value of GoogleTransactionId
	 */
	public final java.lang.String getGoogleTransactionId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.GoogleTransactionId.toString());
	}

	/**
	 * Set value of GoogleTransactionId
	 * @param googletransactionid
	 */
	public final void setGoogleTransactionId(java.lang.String googletransactionid)
	{
		setGoogleTransactionId(getContext(), googletransactionid);
	}

	/**
	 * Set value of GoogleTransactionId
	 * @param context
	 * @param googletransactionid
	 */
	public final void setGoogleTransactionId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String googletransactionid)
	{
		getMendixObject().setValue(context, MemberNames.GoogleTransactionId.toString(), googletransactionid);
	}

	/**
	 * @return value of GlobalId
	 */
	public final java.lang.String getGlobalId()
	{
		return getGlobalId(getContext());
	}

	/**
	 * @param context
	 * @return value of GlobalId
	 */
	public final java.lang.String getGlobalId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.GlobalId.toString());
	}

	/**
	 * Set value of GlobalId
	 * @param globalid
	 */
	public final void setGlobalId(java.lang.String globalid)
	{
		setGlobalId(getContext(), globalid);
	}

	/**
	 * Set value of GlobalId
	 * @param context
	 * @param globalid
	 */
	public final void setGlobalId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String globalid)
	{
		getMendixObject().setValue(context, MemberNames.GlobalId.toString(), globalid);
	}

	/**
	 * @return value of NetworkTokenized
	 */
	public final java.lang.Boolean getNetworkTokenized()
	{
		return getNetworkTokenized(getContext());
	}

	/**
	 * @param context
	 * @return value of NetworkTokenized
	 */
	public final java.lang.Boolean getNetworkTokenized(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.NetworkTokenized.toString());
	}

	/**
	 * Set value of NetworkTokenized
	 * @param networktokenized
	 */
	public final void setNetworkTokenized(java.lang.Boolean networktokenized)
	{
		setNetworkTokenized(getContext(), networktokenized);
	}

	/**
	 * Set value of NetworkTokenized
	 * @param context
	 * @param networktokenized
	 */
	public final void setNetworkTokenized(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean networktokenized)
	{
		getMendixObject().setValue(context, MemberNames.NetworkTokenized.toString(), networktokenized);
	}

	/**
	 * @return value of AndroidPayDetails_Transaction
	 */
	public final braintreegateway.proxies.Transaction getAndroidPayDetails_Transaction() throws com.mendix.core.CoreException
	{
		return getAndroidPayDetails_Transaction(getContext());
	}

	/**
	 * @param context
	 * @return value of AndroidPayDetails_Transaction
	 */
	public final braintreegateway.proxies.Transaction getAndroidPayDetails_Transaction(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		braintreegateway.proxies.Transaction result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.AndroidPayDetails_Transaction.toString());
		if (identifier != null)
			result = braintreegateway.proxies.Transaction.load(context, identifier);
		return result;
	}

	/**
	 * Set value of AndroidPayDetails_Transaction
	 * @param androidpaydetails_transaction
	 */
	public final void setAndroidPayDetails_Transaction(braintreegateway.proxies.Transaction androidpaydetails_transaction)
	{
		setAndroidPayDetails_Transaction(getContext(), androidpaydetails_transaction);
	}

	/**
	 * Set value of AndroidPayDetails_Transaction
	 * @param context
	 * @param androidpaydetails_transaction
	 */
	public final void setAndroidPayDetails_Transaction(com.mendix.systemwideinterfaces.core.IContext context, braintreegateway.proxies.Transaction androidpaydetails_transaction)
	{
		if (androidpaydetails_transaction == null)
			getMendixObject().setValue(context, MemberNames.AndroidPayDetails_Transaction.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.AndroidPayDetails_Transaction.toString(), androidpaydetails_transaction.getMendixObject().getId());
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final braintreegateway.proxies.AndroidPayDetails that = (braintreegateway.proxies.AndroidPayDetails) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "BraintreeGateway.AndroidPayDetails";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
