// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package braintreegateway.proxies;

public class ApplePayDetails extends braintreegateway.proxies.PaymentType
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "BraintreeGateway.ApplePayDetails";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		PaymentInstrumentName("PaymentInstrumentName"),
		SourceDescription("SourceDescription"),
		CardholderName("CardholderName"),
		GlobalId("GlobalId"),
		CardType("CardType"),
		ExpirationMonth("ExpirationMonth"),
		ExpirationYear("ExpirationYear"),
		Debit("Debit"),
		IssuingBank("IssuingBank"),
		Bin("Bin"),
		Prepaid("Prepaid"),
		Last4("Last4"),
		Payroll("Payroll"),
		CountryOfIssuance("CountryOfIssuance"),
		Healthcare("Healthcare"),
		Commercial("Commercial"),
		DurbinRegulated("DurbinRegulated"),
		ProductId("ProductId"),
		Token("Token"),
		ImageUrl("ImageUrl"),
		ApplePayDetails_Transaction("BraintreeGateway.ApplePayDetails_Transaction");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ApplePayDetails(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "BraintreeGateway.ApplePayDetails"));
	}

	protected ApplePayDetails(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject applePayDetailsMendixObject)
	{
		super(context, applePayDetailsMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("BraintreeGateway.ApplePayDetails", applePayDetailsMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a BraintreeGateway.ApplePayDetails");
	}

	/**
	 * @deprecated Use 'ApplePayDetails.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static braintreegateway.proxies.ApplePayDetails initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return braintreegateway.proxies.ApplePayDetails.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static braintreegateway.proxies.ApplePayDetails initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new braintreegateway.proxies.ApplePayDetails(context, mendixObject);
	}

	public static braintreegateway.proxies.ApplePayDetails load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return braintreegateway.proxies.ApplePayDetails.initialize(context, mendixObject);
	}

	/**
	 * @return value of PaymentInstrumentName
	 */
	public final java.lang.String getPaymentInstrumentName()
	{
		return getPaymentInstrumentName(getContext());
	}

	/**
	 * @param context
	 * @return value of PaymentInstrumentName
	 */
	public final java.lang.String getPaymentInstrumentName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PaymentInstrumentName.toString());
	}

	/**
	 * Set value of PaymentInstrumentName
	 * @param paymentinstrumentname
	 */
	public final void setPaymentInstrumentName(java.lang.String paymentinstrumentname)
	{
		setPaymentInstrumentName(getContext(), paymentinstrumentname);
	}

	/**
	 * Set value of PaymentInstrumentName
	 * @param context
	 * @param paymentinstrumentname
	 */
	public final void setPaymentInstrumentName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String paymentinstrumentname)
	{
		getMendixObject().setValue(context, MemberNames.PaymentInstrumentName.toString(), paymentinstrumentname);
	}

	/**
	 * @return value of SourceDescription
	 */
	public final java.lang.String getSourceDescription()
	{
		return getSourceDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of SourceDescription
	 */
	public final java.lang.String getSourceDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SourceDescription.toString());
	}

	/**
	 * Set value of SourceDescription
	 * @param sourcedescription
	 */
	public final void setSourceDescription(java.lang.String sourcedescription)
	{
		setSourceDescription(getContext(), sourcedescription);
	}

	/**
	 * Set value of SourceDescription
	 * @param context
	 * @param sourcedescription
	 */
	public final void setSourceDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String sourcedescription)
	{
		getMendixObject().setValue(context, MemberNames.SourceDescription.toString(), sourcedescription);
	}

	/**
	 * @return value of CardholderName
	 */
	public final java.lang.String getCardholderName()
	{
		return getCardholderName(getContext());
	}

	/**
	 * @param context
	 * @return value of CardholderName
	 */
	public final java.lang.String getCardholderName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CardholderName.toString());
	}

	/**
	 * Set value of CardholderName
	 * @param cardholdername
	 */
	public final void setCardholderName(java.lang.String cardholdername)
	{
		setCardholderName(getContext(), cardholdername);
	}

	/**
	 * Set value of CardholderName
	 * @param context
	 * @param cardholdername
	 */
	public final void setCardholderName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String cardholdername)
	{
		getMendixObject().setValue(context, MemberNames.CardholderName.toString(), cardholdername);
	}

	/**
	 * @return value of GlobalId
	 */
	public final java.lang.String getGlobalId()
	{
		return getGlobalId(getContext());
	}

	/**
	 * @param context
	 * @return value of GlobalId
	 */
	public final java.lang.String getGlobalId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.GlobalId.toString());
	}

	/**
	 * Set value of GlobalId
	 * @param globalid
	 */
	public final void setGlobalId(java.lang.String globalid)
	{
		setGlobalId(getContext(), globalid);
	}

	/**
	 * Set value of GlobalId
	 * @param context
	 * @param globalid
	 */
	public final void setGlobalId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String globalid)
	{
		getMendixObject().setValue(context, MemberNames.GlobalId.toString(), globalid);
	}

	/**
	 * @return value of ApplePayDetails_Transaction
	 */
	public final braintreegateway.proxies.Transaction getApplePayDetails_Transaction() throws com.mendix.core.CoreException
	{
		return getApplePayDetails_Transaction(getContext());
	}

	/**
	 * @param context
	 * @return value of ApplePayDetails_Transaction
	 */
	public final braintreegateway.proxies.Transaction getApplePayDetails_Transaction(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		braintreegateway.proxies.Transaction result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ApplePayDetails_Transaction.toString());
		if (identifier != null)
			result = braintreegateway.proxies.Transaction.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ApplePayDetails_Transaction
	 * @param applepaydetails_transaction
	 */
	public final void setApplePayDetails_Transaction(braintreegateway.proxies.Transaction applepaydetails_transaction)
	{
		setApplePayDetails_Transaction(getContext(), applepaydetails_transaction);
	}

	/**
	 * Set value of ApplePayDetails_Transaction
	 * @param context
	 * @param applepaydetails_transaction
	 */
	public final void setApplePayDetails_Transaction(com.mendix.systemwideinterfaces.core.IContext context, braintreegateway.proxies.Transaction applepaydetails_transaction)
	{
		if (applepaydetails_transaction == null)
			getMendixObject().setValue(context, MemberNames.ApplePayDetails_Transaction.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ApplePayDetails_Transaction.toString(), applepaydetails_transaction.getMendixObject().getId());
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final braintreegateway.proxies.ApplePayDetails that = (braintreegateway.proxies.ApplePayDetails) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "BraintreeGateway.ApplePayDetails";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
