// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package braintreegateway.proxies;

public class CreditCard extends braintreegateway.proxies.PaymentType
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "BraintreeGateway.CreditCard";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		BillingAddress("BillingAddress"),
		CardholderName("CardholderName"),
		CreatedAt("CreatedAt"),
		CustomerId("CustomerId"),
		CustomerLocation("CustomerLocation"),
		UniqueNumberIdentifier("UniqueNumberIdentifier"),
		UpdatedAt("UpdatedAt"),
		Verification("Verification"),
		AccountType("AccountType"),
		_default("_default"),
		ExpirationDate("ExpirationDate"),
		Expired("Expired"),
		VenmoSdk("VenmoSdk"),
		NetworkTokenized("NetworkTokenized"),
		MaskedNumber("MaskedNumber"),
		CardType("CardType"),
		ExpirationMonth("ExpirationMonth"),
		ExpirationYear("ExpirationYear"),
		Debit("Debit"),
		IssuingBank("IssuingBank"),
		Bin("Bin"),
		Prepaid("Prepaid"),
		Last4("Last4"),
		Payroll("Payroll"),
		CountryOfIssuance("CountryOfIssuance"),
		Healthcare("Healthcare"),
		Commercial("Commercial"),
		DurbinRegulated("DurbinRegulated"),
		ProductId("ProductId"),
		Token("Token"),
		ImageUrl("ImageUrl"),
		CreditCard_Transaction("BraintreeGateway.CreditCard_Transaction");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public CreditCard(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "BraintreeGateway.CreditCard"));
	}

	protected CreditCard(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject creditCardMendixObject)
	{
		super(context, creditCardMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("BraintreeGateway.CreditCard", creditCardMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a BraintreeGateway.CreditCard");
	}

	/**
	 * @deprecated Use 'CreditCard.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static braintreegateway.proxies.CreditCard initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return braintreegateway.proxies.CreditCard.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static braintreegateway.proxies.CreditCard initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new braintreegateway.proxies.CreditCard(context, mendixObject);
	}

	public static braintreegateway.proxies.CreditCard load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return braintreegateway.proxies.CreditCard.initialize(context, mendixObject);
	}

	/**
	 * @return value of BillingAddress
	 */
	public final java.lang.String getBillingAddress()
	{
		return getBillingAddress(getContext());
	}

	/**
	 * @param context
	 * @return value of BillingAddress
	 */
	public final java.lang.String getBillingAddress(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.BillingAddress.toString());
	}

	/**
	 * Set value of BillingAddress
	 * @param billingaddress
	 */
	public final void setBillingAddress(java.lang.String billingaddress)
	{
		setBillingAddress(getContext(), billingaddress);
	}

	/**
	 * Set value of BillingAddress
	 * @param context
	 * @param billingaddress
	 */
	public final void setBillingAddress(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String billingaddress)
	{
		getMendixObject().setValue(context, MemberNames.BillingAddress.toString(), billingaddress);
	}

	/**
	 * @return value of CardholderName
	 */
	public final java.lang.String getCardholderName()
	{
		return getCardholderName(getContext());
	}

	/**
	 * @param context
	 * @return value of CardholderName
	 */
	public final java.lang.String getCardholderName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CardholderName.toString());
	}

	/**
	 * Set value of CardholderName
	 * @param cardholdername
	 */
	public final void setCardholderName(java.lang.String cardholdername)
	{
		setCardholderName(getContext(), cardholdername);
	}

	/**
	 * Set value of CardholderName
	 * @param context
	 * @param cardholdername
	 */
	public final void setCardholderName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String cardholdername)
	{
		getMendixObject().setValue(context, MemberNames.CardholderName.toString(), cardholdername);
	}

	/**
	 * @return value of CreatedAt
	 */
	public final java.lang.Long getCreatedAt()
	{
		return getCreatedAt(getContext());
	}

	/**
	 * @param context
	 * @return value of CreatedAt
	 */
	public final java.lang.Long getCreatedAt(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.CreatedAt.toString());
	}

	/**
	 * Set value of CreatedAt
	 * @param createdat
	 */
	public final void setCreatedAt(java.lang.Long createdat)
	{
		setCreatedAt(getContext(), createdat);
	}

	/**
	 * Set value of CreatedAt
	 * @param context
	 * @param createdat
	 */
	public final void setCreatedAt(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long createdat)
	{
		getMendixObject().setValue(context, MemberNames.CreatedAt.toString(), createdat);
	}

	/**
	 * @return value of CustomerId
	 */
	public final java.lang.String getCustomerId()
	{
		return getCustomerId(getContext());
	}

	/**
	 * @param context
	 * @return value of CustomerId
	 */
	public final java.lang.String getCustomerId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CustomerId.toString());
	}

	/**
	 * Set value of CustomerId
	 * @param customerid
	 */
	public final void setCustomerId(java.lang.String customerid)
	{
		setCustomerId(getContext(), customerid);
	}

	/**
	 * Set value of CustomerId
	 * @param context
	 * @param customerid
	 */
	public final void setCustomerId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String customerid)
	{
		getMendixObject().setValue(context, MemberNames.CustomerId.toString(), customerid);
	}

	/**
	 * @return value of CustomerLocation
	 */
	public final java.lang.String getCustomerLocation()
	{
		return getCustomerLocation(getContext());
	}

	/**
	 * @param context
	 * @return value of CustomerLocation
	 */
	public final java.lang.String getCustomerLocation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CustomerLocation.toString());
	}

	/**
	 * Set value of CustomerLocation
	 * @param customerlocation
	 */
	public final void setCustomerLocation(java.lang.String customerlocation)
	{
		setCustomerLocation(getContext(), customerlocation);
	}

	/**
	 * Set value of CustomerLocation
	 * @param context
	 * @param customerlocation
	 */
	public final void setCustomerLocation(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String customerlocation)
	{
		getMendixObject().setValue(context, MemberNames.CustomerLocation.toString(), customerlocation);
	}

	/**
	 * @return value of UniqueNumberIdentifier
	 */
	public final java.lang.String getUniqueNumberIdentifier()
	{
		return getUniqueNumberIdentifier(getContext());
	}

	/**
	 * @param context
	 * @return value of UniqueNumberIdentifier
	 */
	public final java.lang.String getUniqueNumberIdentifier(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UniqueNumberIdentifier.toString());
	}

	/**
	 * Set value of UniqueNumberIdentifier
	 * @param uniquenumberidentifier
	 */
	public final void setUniqueNumberIdentifier(java.lang.String uniquenumberidentifier)
	{
		setUniqueNumberIdentifier(getContext(), uniquenumberidentifier);
	}

	/**
	 * Set value of UniqueNumberIdentifier
	 * @param context
	 * @param uniquenumberidentifier
	 */
	public final void setUniqueNumberIdentifier(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String uniquenumberidentifier)
	{
		getMendixObject().setValue(context, MemberNames.UniqueNumberIdentifier.toString(), uniquenumberidentifier);
	}

	/**
	 * @return value of UpdatedAt
	 */
	public final java.lang.Long getUpdatedAt()
	{
		return getUpdatedAt(getContext());
	}

	/**
	 * @param context
	 * @return value of UpdatedAt
	 */
	public final java.lang.Long getUpdatedAt(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.UpdatedAt.toString());
	}

	/**
	 * Set value of UpdatedAt
	 * @param updatedat
	 */
	public final void setUpdatedAt(java.lang.Long updatedat)
	{
		setUpdatedAt(getContext(), updatedat);
	}

	/**
	 * Set value of UpdatedAt
	 * @param context
	 * @param updatedat
	 */
	public final void setUpdatedAt(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long updatedat)
	{
		getMendixObject().setValue(context, MemberNames.UpdatedAt.toString(), updatedat);
	}

	/**
	 * @return value of Verification
	 */
	public final java.lang.String getVerification()
	{
		return getVerification(getContext());
	}

	/**
	 * @param context
	 * @return value of Verification
	 */
	public final java.lang.String getVerification(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Verification.toString());
	}

	/**
	 * Set value of Verification
	 * @param verification
	 */
	public final void setVerification(java.lang.String verification)
	{
		setVerification(getContext(), verification);
	}

	/**
	 * Set value of Verification
	 * @param context
	 * @param verification
	 */
	public final void setVerification(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String verification)
	{
		getMendixObject().setValue(context, MemberNames.Verification.toString(), verification);
	}

	/**
	 * @return value of AccountType
	 */
	public final java.lang.String getAccountType()
	{
		return getAccountType(getContext());
	}

	/**
	 * @param context
	 * @return value of AccountType
	 */
	public final java.lang.String getAccountType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AccountType.toString());
	}

	/**
	 * Set value of AccountType
	 * @param accounttype
	 */
	public final void setAccountType(java.lang.String accounttype)
	{
		setAccountType(getContext(), accounttype);
	}

	/**
	 * Set value of AccountType
	 * @param context
	 * @param accounttype
	 */
	public final void setAccountType(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String accounttype)
	{
		getMendixObject().setValue(context, MemberNames.AccountType.toString(), accounttype);
	}

	/**
	 * @return value of _default
	 */
	public final java.lang.Boolean get_default()
	{
		return get_default(getContext());
	}

	/**
	 * @param context
	 * @return value of _default
	 */
	public final java.lang.Boolean get_default(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames._default.toString());
	}

	/**
	 * Set value of _default
	 * @param _default
	 */
	public final void set_default(java.lang.Boolean _default)
	{
		set_default(getContext(), _default);
	}

	/**
	 * Set value of _default
	 * @param context
	 * @param _default
	 */
	public final void set_default(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean _default)
	{
		getMendixObject().setValue(context, MemberNames._default.toString(), _default);
	}

	/**
	 * @return value of ExpirationDate
	 */
	public final java.lang.String getExpirationDate()
	{
		return getExpirationDate(getContext());
	}

	/**
	 * @param context
	 * @return value of ExpirationDate
	 */
	public final java.lang.String getExpirationDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ExpirationDate.toString());
	}

	/**
	 * Set value of ExpirationDate
	 * @param expirationdate
	 */
	public final void setExpirationDate(java.lang.String expirationdate)
	{
		setExpirationDate(getContext(), expirationdate);
	}

	/**
	 * Set value of ExpirationDate
	 * @param context
	 * @param expirationdate
	 */
	public final void setExpirationDate(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String expirationdate)
	{
		getMendixObject().setValue(context, MemberNames.ExpirationDate.toString(), expirationdate);
	}

	/**
	 * @return value of Expired
	 */
	public final java.lang.Boolean getExpired()
	{
		return getExpired(getContext());
	}

	/**
	 * @param context
	 * @return value of Expired
	 */
	public final java.lang.Boolean getExpired(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Expired.toString());
	}

	/**
	 * Set value of Expired
	 * @param expired
	 */
	public final void setExpired(java.lang.Boolean expired)
	{
		setExpired(getContext(), expired);
	}

	/**
	 * Set value of Expired
	 * @param context
	 * @param expired
	 */
	public final void setExpired(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean expired)
	{
		getMendixObject().setValue(context, MemberNames.Expired.toString(), expired);
	}

	/**
	 * @return value of VenmoSdk
	 */
	public final java.lang.Boolean getVenmoSdk()
	{
		return getVenmoSdk(getContext());
	}

	/**
	 * @param context
	 * @return value of VenmoSdk
	 */
	public final java.lang.Boolean getVenmoSdk(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.VenmoSdk.toString());
	}

	/**
	 * Set value of VenmoSdk
	 * @param venmosdk
	 */
	public final void setVenmoSdk(java.lang.Boolean venmosdk)
	{
		setVenmoSdk(getContext(), venmosdk);
	}

	/**
	 * Set value of VenmoSdk
	 * @param context
	 * @param venmosdk
	 */
	public final void setVenmoSdk(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean venmosdk)
	{
		getMendixObject().setValue(context, MemberNames.VenmoSdk.toString(), venmosdk);
	}

	/**
	 * @return value of NetworkTokenized
	 */
	public final java.lang.Boolean getNetworkTokenized()
	{
		return getNetworkTokenized(getContext());
	}

	/**
	 * @param context
	 * @return value of NetworkTokenized
	 */
	public final java.lang.Boolean getNetworkTokenized(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.NetworkTokenized.toString());
	}

	/**
	 * Set value of NetworkTokenized
	 * @param networktokenized
	 */
	public final void setNetworkTokenized(java.lang.Boolean networktokenized)
	{
		setNetworkTokenized(getContext(), networktokenized);
	}

	/**
	 * Set value of NetworkTokenized
	 * @param context
	 * @param networktokenized
	 */
	public final void setNetworkTokenized(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean networktokenized)
	{
		getMendixObject().setValue(context, MemberNames.NetworkTokenized.toString(), networktokenized);
	}

	/**
	 * @return value of MaskedNumber
	 */
	public final java.lang.String getMaskedNumber()
	{
		return getMaskedNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of MaskedNumber
	 */
	public final java.lang.String getMaskedNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MaskedNumber.toString());
	}

	/**
	 * Set value of MaskedNumber
	 * @param maskednumber
	 */
	public final void setMaskedNumber(java.lang.String maskednumber)
	{
		setMaskedNumber(getContext(), maskednumber);
	}

	/**
	 * Set value of MaskedNumber
	 * @param context
	 * @param maskednumber
	 */
	public final void setMaskedNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String maskednumber)
	{
		getMendixObject().setValue(context, MemberNames.MaskedNumber.toString(), maskednumber);
	}

	/**
	 * @return value of CreditCard_Transaction
	 */
	public final braintreegateway.proxies.Transaction getCreditCard_Transaction() throws com.mendix.core.CoreException
	{
		return getCreditCard_Transaction(getContext());
	}

	/**
	 * @param context
	 * @return value of CreditCard_Transaction
	 */
	public final braintreegateway.proxies.Transaction getCreditCard_Transaction(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		braintreegateway.proxies.Transaction result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.CreditCard_Transaction.toString());
		if (identifier != null)
			result = braintreegateway.proxies.Transaction.load(context, identifier);
		return result;
	}

	/**
	 * Set value of CreditCard_Transaction
	 * @param creditcard_transaction
	 */
	public final void setCreditCard_Transaction(braintreegateway.proxies.Transaction creditcard_transaction)
	{
		setCreditCard_Transaction(getContext(), creditcard_transaction);
	}

	/**
	 * Set value of CreditCard_Transaction
	 * @param context
	 * @param creditcard_transaction
	 */
	public final void setCreditCard_Transaction(com.mendix.systemwideinterfaces.core.IContext context, braintreegateway.proxies.Transaction creditcard_transaction)
	{
		if (creditcard_transaction == null)
			getMendixObject().setValue(context, MemberNames.CreditCard_Transaction.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.CreditCard_Transaction.toString(), creditcard_transaction.getMendixObject().getId());
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final braintreegateway.proxies.CreditCard that = (braintreegateway.proxies.CreditCard) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "BraintreeGateway.CreditCard";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
