// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package braintreegateway.proxies;

public class DisbursementDetails
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject disbursementDetailsMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "BraintreeGateway.DisbursementDetails";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		DisbursementDate("DisbursementDate"),
		SettlementCurrencyIsoCode("SettlementCurrencyIsoCode"),
		FundsHeld("FundsHeld"),
		Success("Success"),
		SettlementCurrencyExchangeRate("SettlementCurrencyExchangeRate"),
		SettlementAmount("SettlementAmount"),
		Valid("Valid"),
		DisbursementDetails_Transaction("BraintreeGateway.DisbursementDetails_Transaction");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public DisbursementDetails(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "BraintreeGateway.DisbursementDetails"));
	}

	protected DisbursementDetails(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject disbursementDetailsMendixObject)
	{
		if (disbursementDetailsMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("BraintreeGateway.DisbursementDetails", disbursementDetailsMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a BraintreeGateway.DisbursementDetails");

		this.disbursementDetailsMendixObject = disbursementDetailsMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'DisbursementDetails.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static braintreegateway.proxies.DisbursementDetails initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return braintreegateway.proxies.DisbursementDetails.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static braintreegateway.proxies.DisbursementDetails initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new braintreegateway.proxies.DisbursementDetails(context, mendixObject);
	}

	public static braintreegateway.proxies.DisbursementDetails load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return braintreegateway.proxies.DisbursementDetails.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of DisbursementDate
	 */
	public final java.lang.Long getDisbursementDate()
	{
		return getDisbursementDate(getContext());
	}

	/**
	 * @param context
	 * @return value of DisbursementDate
	 */
	public final java.lang.Long getDisbursementDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.DisbursementDate.toString());
	}

	/**
	 * Set value of DisbursementDate
	 * @param disbursementdate
	 */
	public final void setDisbursementDate(java.lang.Long disbursementdate)
	{
		setDisbursementDate(getContext(), disbursementdate);
	}

	/**
	 * Set value of DisbursementDate
	 * @param context
	 * @param disbursementdate
	 */
	public final void setDisbursementDate(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long disbursementdate)
	{
		getMendixObject().setValue(context, MemberNames.DisbursementDate.toString(), disbursementdate);
	}

	/**
	 * @return value of SettlementCurrencyIsoCode
	 */
	public final java.lang.String getSettlementCurrencyIsoCode()
	{
		return getSettlementCurrencyIsoCode(getContext());
	}

	/**
	 * @param context
	 * @return value of SettlementCurrencyIsoCode
	 */
	public final java.lang.String getSettlementCurrencyIsoCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SettlementCurrencyIsoCode.toString());
	}

	/**
	 * Set value of SettlementCurrencyIsoCode
	 * @param settlementcurrencyisocode
	 */
	public final void setSettlementCurrencyIsoCode(java.lang.String settlementcurrencyisocode)
	{
		setSettlementCurrencyIsoCode(getContext(), settlementcurrencyisocode);
	}

	/**
	 * Set value of SettlementCurrencyIsoCode
	 * @param context
	 * @param settlementcurrencyisocode
	 */
	public final void setSettlementCurrencyIsoCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String settlementcurrencyisocode)
	{
		getMendixObject().setValue(context, MemberNames.SettlementCurrencyIsoCode.toString(), settlementcurrencyisocode);
	}

	/**
	 * @return value of FundsHeld
	 */
	public final java.lang.Boolean getFundsHeld()
	{
		return getFundsHeld(getContext());
	}

	/**
	 * @param context
	 * @return value of FundsHeld
	 */
	public final java.lang.Boolean getFundsHeld(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.FundsHeld.toString());
	}

	/**
	 * Set value of FundsHeld
	 * @param fundsheld
	 */
	public final void setFundsHeld(java.lang.Boolean fundsheld)
	{
		setFundsHeld(getContext(), fundsheld);
	}

	/**
	 * Set value of FundsHeld
	 * @param context
	 * @param fundsheld
	 */
	public final void setFundsHeld(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean fundsheld)
	{
		getMendixObject().setValue(context, MemberNames.FundsHeld.toString(), fundsheld);
	}

	/**
	 * @return value of Success
	 */
	public final java.lang.Boolean getSuccess()
	{
		return getSuccess(getContext());
	}

	/**
	 * @param context
	 * @return value of Success
	 */
	public final java.lang.Boolean getSuccess(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Success.toString());
	}

	/**
	 * Set value of Success
	 * @param success
	 */
	public final void setSuccess(java.lang.Boolean success)
	{
		setSuccess(getContext(), success);
	}

	/**
	 * Set value of Success
	 * @param context
	 * @param success
	 */
	public final void setSuccess(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean success)
	{
		getMendixObject().setValue(context, MemberNames.Success.toString(), success);
	}

	/**
	 * @return value of SettlementCurrencyExchangeRate
	 */
	public final java.lang.String getSettlementCurrencyExchangeRate()
	{
		return getSettlementCurrencyExchangeRate(getContext());
	}

	/**
	 * @param context
	 * @return value of SettlementCurrencyExchangeRate
	 */
	public final java.lang.String getSettlementCurrencyExchangeRate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SettlementCurrencyExchangeRate.toString());
	}

	/**
	 * Set value of SettlementCurrencyExchangeRate
	 * @param settlementcurrencyexchangerate
	 */
	public final void setSettlementCurrencyExchangeRate(java.lang.String settlementcurrencyexchangerate)
	{
		setSettlementCurrencyExchangeRate(getContext(), settlementcurrencyexchangerate);
	}

	/**
	 * Set value of SettlementCurrencyExchangeRate
	 * @param context
	 * @param settlementcurrencyexchangerate
	 */
	public final void setSettlementCurrencyExchangeRate(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String settlementcurrencyexchangerate)
	{
		getMendixObject().setValue(context, MemberNames.SettlementCurrencyExchangeRate.toString(), settlementcurrencyexchangerate);
	}

	/**
	 * @return value of SettlementAmount
	 */
	public final java.math.BigDecimal getSettlementAmount()
	{
		return getSettlementAmount(getContext());
	}

	/**
	 * @param context
	 * @return value of SettlementAmount
	 */
	public final java.math.BigDecimal getSettlementAmount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.SettlementAmount.toString());
	}

	/**
	 * Set value of SettlementAmount
	 * @param settlementamount
	 */
	public final void setSettlementAmount(java.math.BigDecimal settlementamount)
	{
		setSettlementAmount(getContext(), settlementamount);
	}

	/**
	 * Set value of SettlementAmount
	 * @param context
	 * @param settlementamount
	 */
	public final void setSettlementAmount(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal settlementamount)
	{
		getMendixObject().setValue(context, MemberNames.SettlementAmount.toString(), settlementamount);
	}

	/**
	 * @return value of Valid
	 */
	public final java.lang.Boolean getValid()
	{
		return getValid(getContext());
	}

	/**
	 * @param context
	 * @return value of Valid
	 */
	public final java.lang.Boolean getValid(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Valid.toString());
	}

	/**
	 * Set value of Valid
	 * @param valid
	 */
	public final void setValid(java.lang.Boolean valid)
	{
		setValid(getContext(), valid);
	}

	/**
	 * Set value of Valid
	 * @param context
	 * @param valid
	 */
	public final void setValid(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean valid)
	{
		getMendixObject().setValue(context, MemberNames.Valid.toString(), valid);
	}

	/**
	 * @return value of DisbursementDetails_Transaction
	 */
	public final braintreegateway.proxies.Transaction getDisbursementDetails_Transaction() throws com.mendix.core.CoreException
	{
		return getDisbursementDetails_Transaction(getContext());
	}

	/**
	 * @param context
	 * @return value of DisbursementDetails_Transaction
	 */
	public final braintreegateway.proxies.Transaction getDisbursementDetails_Transaction(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		braintreegateway.proxies.Transaction result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DisbursementDetails_Transaction.toString());
		if (identifier != null)
			result = braintreegateway.proxies.Transaction.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DisbursementDetails_Transaction
	 * @param disbursementdetails_transaction
	 */
	public final void setDisbursementDetails_Transaction(braintreegateway.proxies.Transaction disbursementdetails_transaction)
	{
		setDisbursementDetails_Transaction(getContext(), disbursementdetails_transaction);
	}

	/**
	 * Set value of DisbursementDetails_Transaction
	 * @param context
	 * @param disbursementdetails_transaction
	 */
	public final void setDisbursementDetails_Transaction(com.mendix.systemwideinterfaces.core.IContext context, braintreegateway.proxies.Transaction disbursementdetails_transaction)
	{
		if (disbursementdetails_transaction == null)
			getMendixObject().setValue(context, MemberNames.DisbursementDetails_Transaction.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DisbursementDetails_Transaction.toString(), disbursementdetails_transaction.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return disbursementDetailsMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final braintreegateway.proxies.DisbursementDetails that = (braintreegateway.proxies.DisbursementDetails) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "BraintreeGateway.DisbursementDetails";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
