// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package braintreegateway.proxies;

public class PayPalDetails extends braintreegateway.proxies.GenericPayment
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "BraintreeGateway.PayPalDetails";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		PayerEmail("PayerEmail"),
		PaymentId("PaymentId"),
		AuthorizationId("AuthorizationId"),
		DebugId("DebugId"),
		PayeeId("PayeeId"),
		PayeeEmail("PayeeEmail"),
		CustomField("CustomField"),
		PayerId("PayerId"),
		PayerFirstName("PayerFirstName"),
		PayerLastName("PayerLastName"),
		PayerStatus("PayerStatus"),
		SellerProtectionStatus("SellerProtectionStatus"),
		CaptureId("CaptureId"),
		RefundId("RefundId"),
		TransactionFeeAmount("TransactionFeeAmount"),
		TransactionFeeCurrencyIsoCode("TransactionFeeCurrencyIsoCode"),
		RefundFromTransactionFeeAmount("RefundFromTransactionFeeAmount"),
		RefundFromTransactionFeeCurrencyIsoCode("RefundFromTransactionFeeCurrencyIsoCode"),
		Description("Description"),
		ImplicitlyVaultedPaymentMethodToken("ImplicitlyVaultedPaymentMethodToken"),
		ImplicitlyVaultedPaymentMethodGlobalId("ImplicitlyVaultedPaymentMethodGlobalId"),
		BillingAgreementId("BillingAgreementId"),
		Token("Token"),
		ImageUrl("ImageUrl"),
		PayPalDetails_Transaction("BraintreeGateway.PayPalDetails_Transaction");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public PayPalDetails(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "BraintreeGateway.PayPalDetails"));
	}

	protected PayPalDetails(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject payPalDetailsMendixObject)
	{
		super(context, payPalDetailsMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("BraintreeGateway.PayPalDetails", payPalDetailsMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a BraintreeGateway.PayPalDetails");
	}

	/**
	 * @deprecated Use 'PayPalDetails.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static braintreegateway.proxies.PayPalDetails initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return braintreegateway.proxies.PayPalDetails.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static braintreegateway.proxies.PayPalDetails initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new braintreegateway.proxies.PayPalDetails(context, mendixObject);
	}

	public static braintreegateway.proxies.PayPalDetails load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return braintreegateway.proxies.PayPalDetails.initialize(context, mendixObject);
	}

	/**
	 * @return value of PayerEmail
	 */
	public final java.lang.String getPayerEmail()
	{
		return getPayerEmail(getContext());
	}

	/**
	 * @param context
	 * @return value of PayerEmail
	 */
	public final java.lang.String getPayerEmail(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PayerEmail.toString());
	}

	/**
	 * Set value of PayerEmail
	 * @param payeremail
	 */
	public final void setPayerEmail(java.lang.String payeremail)
	{
		setPayerEmail(getContext(), payeremail);
	}

	/**
	 * Set value of PayerEmail
	 * @param context
	 * @param payeremail
	 */
	public final void setPayerEmail(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String payeremail)
	{
		getMendixObject().setValue(context, MemberNames.PayerEmail.toString(), payeremail);
	}

	/**
	 * @return value of PaymentId
	 */
	public final java.lang.String getPaymentId()
	{
		return getPaymentId(getContext());
	}

	/**
	 * @param context
	 * @return value of PaymentId
	 */
	public final java.lang.String getPaymentId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PaymentId.toString());
	}

	/**
	 * Set value of PaymentId
	 * @param paymentid
	 */
	public final void setPaymentId(java.lang.String paymentid)
	{
		setPaymentId(getContext(), paymentid);
	}

	/**
	 * Set value of PaymentId
	 * @param context
	 * @param paymentid
	 */
	public final void setPaymentId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String paymentid)
	{
		getMendixObject().setValue(context, MemberNames.PaymentId.toString(), paymentid);
	}

	/**
	 * @return value of AuthorizationId
	 */
	public final java.lang.String getAuthorizationId()
	{
		return getAuthorizationId(getContext());
	}

	/**
	 * @param context
	 * @return value of AuthorizationId
	 */
	public final java.lang.String getAuthorizationId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AuthorizationId.toString());
	}

	/**
	 * Set value of AuthorizationId
	 * @param authorizationid
	 */
	public final void setAuthorizationId(java.lang.String authorizationid)
	{
		setAuthorizationId(getContext(), authorizationid);
	}

	/**
	 * Set value of AuthorizationId
	 * @param context
	 * @param authorizationid
	 */
	public final void setAuthorizationId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String authorizationid)
	{
		getMendixObject().setValue(context, MemberNames.AuthorizationId.toString(), authorizationid);
	}

	/**
	 * @return value of DebugId
	 */
	public final java.lang.String getDebugId()
	{
		return getDebugId(getContext());
	}

	/**
	 * @param context
	 * @return value of DebugId
	 */
	public final java.lang.String getDebugId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DebugId.toString());
	}

	/**
	 * Set value of DebugId
	 * @param debugid
	 */
	public final void setDebugId(java.lang.String debugid)
	{
		setDebugId(getContext(), debugid);
	}

	/**
	 * Set value of DebugId
	 * @param context
	 * @param debugid
	 */
	public final void setDebugId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String debugid)
	{
		getMendixObject().setValue(context, MemberNames.DebugId.toString(), debugid);
	}

	/**
	 * @return value of PayeeId
	 */
	public final java.lang.String getPayeeId()
	{
		return getPayeeId(getContext());
	}

	/**
	 * @param context
	 * @return value of PayeeId
	 */
	public final java.lang.String getPayeeId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PayeeId.toString());
	}

	/**
	 * Set value of PayeeId
	 * @param payeeid
	 */
	public final void setPayeeId(java.lang.String payeeid)
	{
		setPayeeId(getContext(), payeeid);
	}

	/**
	 * Set value of PayeeId
	 * @param context
	 * @param payeeid
	 */
	public final void setPayeeId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String payeeid)
	{
		getMendixObject().setValue(context, MemberNames.PayeeId.toString(), payeeid);
	}

	/**
	 * @return value of PayeeEmail
	 */
	public final java.lang.String getPayeeEmail()
	{
		return getPayeeEmail(getContext());
	}

	/**
	 * @param context
	 * @return value of PayeeEmail
	 */
	public final java.lang.String getPayeeEmail(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PayeeEmail.toString());
	}

	/**
	 * Set value of PayeeEmail
	 * @param payeeemail
	 */
	public final void setPayeeEmail(java.lang.String payeeemail)
	{
		setPayeeEmail(getContext(), payeeemail);
	}

	/**
	 * Set value of PayeeEmail
	 * @param context
	 * @param payeeemail
	 */
	public final void setPayeeEmail(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String payeeemail)
	{
		getMendixObject().setValue(context, MemberNames.PayeeEmail.toString(), payeeemail);
	}

	/**
	 * @return value of CustomField
	 */
	public final java.lang.String getCustomField()
	{
		return getCustomField(getContext());
	}

	/**
	 * @param context
	 * @return value of CustomField
	 */
	public final java.lang.String getCustomField(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CustomField.toString());
	}

	/**
	 * Set value of CustomField
	 * @param customfield
	 */
	public final void setCustomField(java.lang.String customfield)
	{
		setCustomField(getContext(), customfield);
	}

	/**
	 * Set value of CustomField
	 * @param context
	 * @param customfield
	 */
	public final void setCustomField(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String customfield)
	{
		getMendixObject().setValue(context, MemberNames.CustomField.toString(), customfield);
	}

	/**
	 * @return value of PayerId
	 */
	public final java.lang.String getPayerId()
	{
		return getPayerId(getContext());
	}

	/**
	 * @param context
	 * @return value of PayerId
	 */
	public final java.lang.String getPayerId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PayerId.toString());
	}

	/**
	 * Set value of PayerId
	 * @param payerid
	 */
	public final void setPayerId(java.lang.String payerid)
	{
		setPayerId(getContext(), payerid);
	}

	/**
	 * Set value of PayerId
	 * @param context
	 * @param payerid
	 */
	public final void setPayerId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String payerid)
	{
		getMendixObject().setValue(context, MemberNames.PayerId.toString(), payerid);
	}

	/**
	 * @return value of PayerFirstName
	 */
	public final java.lang.String getPayerFirstName()
	{
		return getPayerFirstName(getContext());
	}

	/**
	 * @param context
	 * @return value of PayerFirstName
	 */
	public final java.lang.String getPayerFirstName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PayerFirstName.toString());
	}

	/**
	 * Set value of PayerFirstName
	 * @param payerfirstname
	 */
	public final void setPayerFirstName(java.lang.String payerfirstname)
	{
		setPayerFirstName(getContext(), payerfirstname);
	}

	/**
	 * Set value of PayerFirstName
	 * @param context
	 * @param payerfirstname
	 */
	public final void setPayerFirstName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String payerfirstname)
	{
		getMendixObject().setValue(context, MemberNames.PayerFirstName.toString(), payerfirstname);
	}

	/**
	 * @return value of PayerLastName
	 */
	public final java.lang.String getPayerLastName()
	{
		return getPayerLastName(getContext());
	}

	/**
	 * @param context
	 * @return value of PayerLastName
	 */
	public final java.lang.String getPayerLastName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PayerLastName.toString());
	}

	/**
	 * Set value of PayerLastName
	 * @param payerlastname
	 */
	public final void setPayerLastName(java.lang.String payerlastname)
	{
		setPayerLastName(getContext(), payerlastname);
	}

	/**
	 * Set value of PayerLastName
	 * @param context
	 * @param payerlastname
	 */
	public final void setPayerLastName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String payerlastname)
	{
		getMendixObject().setValue(context, MemberNames.PayerLastName.toString(), payerlastname);
	}

	/**
	 * @return value of PayerStatus
	 */
	public final java.lang.String getPayerStatus()
	{
		return getPayerStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of PayerStatus
	 */
	public final java.lang.String getPayerStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PayerStatus.toString());
	}

	/**
	 * Set value of PayerStatus
	 * @param payerstatus
	 */
	public final void setPayerStatus(java.lang.String payerstatus)
	{
		setPayerStatus(getContext(), payerstatus);
	}

	/**
	 * Set value of PayerStatus
	 * @param context
	 * @param payerstatus
	 */
	public final void setPayerStatus(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String payerstatus)
	{
		getMendixObject().setValue(context, MemberNames.PayerStatus.toString(), payerstatus);
	}

	/**
	 * @return value of SellerProtectionStatus
	 */
	public final java.lang.String getSellerProtectionStatus()
	{
		return getSellerProtectionStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of SellerProtectionStatus
	 */
	public final java.lang.String getSellerProtectionStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SellerProtectionStatus.toString());
	}

	/**
	 * Set value of SellerProtectionStatus
	 * @param sellerprotectionstatus
	 */
	public final void setSellerProtectionStatus(java.lang.String sellerprotectionstatus)
	{
		setSellerProtectionStatus(getContext(), sellerprotectionstatus);
	}

	/**
	 * Set value of SellerProtectionStatus
	 * @param context
	 * @param sellerprotectionstatus
	 */
	public final void setSellerProtectionStatus(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String sellerprotectionstatus)
	{
		getMendixObject().setValue(context, MemberNames.SellerProtectionStatus.toString(), sellerprotectionstatus);
	}

	/**
	 * @return value of CaptureId
	 */
	public final java.lang.String getCaptureId()
	{
		return getCaptureId(getContext());
	}

	/**
	 * @param context
	 * @return value of CaptureId
	 */
	public final java.lang.String getCaptureId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CaptureId.toString());
	}

	/**
	 * Set value of CaptureId
	 * @param captureid
	 */
	public final void setCaptureId(java.lang.String captureid)
	{
		setCaptureId(getContext(), captureid);
	}

	/**
	 * Set value of CaptureId
	 * @param context
	 * @param captureid
	 */
	public final void setCaptureId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String captureid)
	{
		getMendixObject().setValue(context, MemberNames.CaptureId.toString(), captureid);
	}

	/**
	 * @return value of RefundId
	 */
	public final java.lang.String getRefundId()
	{
		return getRefundId(getContext());
	}

	/**
	 * @param context
	 * @return value of RefundId
	 */
	public final java.lang.String getRefundId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.RefundId.toString());
	}

	/**
	 * Set value of RefundId
	 * @param refundid
	 */
	public final void setRefundId(java.lang.String refundid)
	{
		setRefundId(getContext(), refundid);
	}

	/**
	 * Set value of RefundId
	 * @param context
	 * @param refundid
	 */
	public final void setRefundId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String refundid)
	{
		getMendixObject().setValue(context, MemberNames.RefundId.toString(), refundid);
	}

	/**
	 * @return value of TransactionFeeAmount
	 */
	public final java.lang.String getTransactionFeeAmount()
	{
		return getTransactionFeeAmount(getContext());
	}

	/**
	 * @param context
	 * @return value of TransactionFeeAmount
	 */
	public final java.lang.String getTransactionFeeAmount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TransactionFeeAmount.toString());
	}

	/**
	 * Set value of TransactionFeeAmount
	 * @param transactionfeeamount
	 */
	public final void setTransactionFeeAmount(java.lang.String transactionfeeamount)
	{
		setTransactionFeeAmount(getContext(), transactionfeeamount);
	}

	/**
	 * Set value of TransactionFeeAmount
	 * @param context
	 * @param transactionfeeamount
	 */
	public final void setTransactionFeeAmount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String transactionfeeamount)
	{
		getMendixObject().setValue(context, MemberNames.TransactionFeeAmount.toString(), transactionfeeamount);
	}

	/**
	 * @return value of TransactionFeeCurrencyIsoCode
	 */
	public final java.lang.String getTransactionFeeCurrencyIsoCode()
	{
		return getTransactionFeeCurrencyIsoCode(getContext());
	}

	/**
	 * @param context
	 * @return value of TransactionFeeCurrencyIsoCode
	 */
	public final java.lang.String getTransactionFeeCurrencyIsoCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TransactionFeeCurrencyIsoCode.toString());
	}

	/**
	 * Set value of TransactionFeeCurrencyIsoCode
	 * @param transactionfeecurrencyisocode
	 */
	public final void setTransactionFeeCurrencyIsoCode(java.lang.String transactionfeecurrencyisocode)
	{
		setTransactionFeeCurrencyIsoCode(getContext(), transactionfeecurrencyisocode);
	}

	/**
	 * Set value of TransactionFeeCurrencyIsoCode
	 * @param context
	 * @param transactionfeecurrencyisocode
	 */
	public final void setTransactionFeeCurrencyIsoCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String transactionfeecurrencyisocode)
	{
		getMendixObject().setValue(context, MemberNames.TransactionFeeCurrencyIsoCode.toString(), transactionfeecurrencyisocode);
	}

	/**
	 * @return value of RefundFromTransactionFeeAmount
	 */
	public final java.lang.String getRefundFromTransactionFeeAmount()
	{
		return getRefundFromTransactionFeeAmount(getContext());
	}

	/**
	 * @param context
	 * @return value of RefundFromTransactionFeeAmount
	 */
	public final java.lang.String getRefundFromTransactionFeeAmount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.RefundFromTransactionFeeAmount.toString());
	}

	/**
	 * Set value of RefundFromTransactionFeeAmount
	 * @param refundfromtransactionfeeamount
	 */
	public final void setRefundFromTransactionFeeAmount(java.lang.String refundfromtransactionfeeamount)
	{
		setRefundFromTransactionFeeAmount(getContext(), refundfromtransactionfeeamount);
	}

	/**
	 * Set value of RefundFromTransactionFeeAmount
	 * @param context
	 * @param refundfromtransactionfeeamount
	 */
	public final void setRefundFromTransactionFeeAmount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String refundfromtransactionfeeamount)
	{
		getMendixObject().setValue(context, MemberNames.RefundFromTransactionFeeAmount.toString(), refundfromtransactionfeeamount);
	}

	/**
	 * @return value of RefundFromTransactionFeeCurrencyIsoCode
	 */
	public final java.lang.String getRefundFromTransactionFeeCurrencyIsoCode()
	{
		return getRefundFromTransactionFeeCurrencyIsoCode(getContext());
	}

	/**
	 * @param context
	 * @return value of RefundFromTransactionFeeCurrencyIsoCode
	 */
	public final java.lang.String getRefundFromTransactionFeeCurrencyIsoCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.RefundFromTransactionFeeCurrencyIsoCode.toString());
	}

	/**
	 * Set value of RefundFromTransactionFeeCurrencyIsoCode
	 * @param refundfromtransactionfeecurrencyisocode
	 */
	public final void setRefundFromTransactionFeeCurrencyIsoCode(java.lang.String refundfromtransactionfeecurrencyisocode)
	{
		setRefundFromTransactionFeeCurrencyIsoCode(getContext(), refundfromtransactionfeecurrencyisocode);
	}

	/**
	 * Set value of RefundFromTransactionFeeCurrencyIsoCode
	 * @param context
	 * @param refundfromtransactionfeecurrencyisocode
	 */
	public final void setRefundFromTransactionFeeCurrencyIsoCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String refundfromtransactionfeecurrencyisocode)
	{
		getMendixObject().setValue(context, MemberNames.RefundFromTransactionFeeCurrencyIsoCode.toString(), refundfromtransactionfeecurrencyisocode);
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @return value of ImplicitlyVaultedPaymentMethodToken
	 */
	public final java.lang.String getImplicitlyVaultedPaymentMethodToken()
	{
		return getImplicitlyVaultedPaymentMethodToken(getContext());
	}

	/**
	 * @param context
	 * @return value of ImplicitlyVaultedPaymentMethodToken
	 */
	public final java.lang.String getImplicitlyVaultedPaymentMethodToken(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ImplicitlyVaultedPaymentMethodToken.toString());
	}

	/**
	 * Set value of ImplicitlyVaultedPaymentMethodToken
	 * @param implicitlyvaultedpaymentmethodtoken
	 */
	public final void setImplicitlyVaultedPaymentMethodToken(java.lang.String implicitlyvaultedpaymentmethodtoken)
	{
		setImplicitlyVaultedPaymentMethodToken(getContext(), implicitlyvaultedpaymentmethodtoken);
	}

	/**
	 * Set value of ImplicitlyVaultedPaymentMethodToken
	 * @param context
	 * @param implicitlyvaultedpaymentmethodtoken
	 */
	public final void setImplicitlyVaultedPaymentMethodToken(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String implicitlyvaultedpaymentmethodtoken)
	{
		getMendixObject().setValue(context, MemberNames.ImplicitlyVaultedPaymentMethodToken.toString(), implicitlyvaultedpaymentmethodtoken);
	}

	/**
	 * @return value of ImplicitlyVaultedPaymentMethodGlobalId
	 */
	public final java.lang.String getImplicitlyVaultedPaymentMethodGlobalId()
	{
		return getImplicitlyVaultedPaymentMethodGlobalId(getContext());
	}

	/**
	 * @param context
	 * @return value of ImplicitlyVaultedPaymentMethodGlobalId
	 */
	public final java.lang.String getImplicitlyVaultedPaymentMethodGlobalId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ImplicitlyVaultedPaymentMethodGlobalId.toString());
	}

	/**
	 * Set value of ImplicitlyVaultedPaymentMethodGlobalId
	 * @param implicitlyvaultedpaymentmethodglobalid
	 */
	public final void setImplicitlyVaultedPaymentMethodGlobalId(java.lang.String implicitlyvaultedpaymentmethodglobalid)
	{
		setImplicitlyVaultedPaymentMethodGlobalId(getContext(), implicitlyvaultedpaymentmethodglobalid);
	}

	/**
	 * Set value of ImplicitlyVaultedPaymentMethodGlobalId
	 * @param context
	 * @param implicitlyvaultedpaymentmethodglobalid
	 */
	public final void setImplicitlyVaultedPaymentMethodGlobalId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String implicitlyvaultedpaymentmethodglobalid)
	{
		getMendixObject().setValue(context, MemberNames.ImplicitlyVaultedPaymentMethodGlobalId.toString(), implicitlyvaultedpaymentmethodglobalid);
	}

	/**
	 * @return value of BillingAgreementId
	 */
	public final java.lang.String getBillingAgreementId()
	{
		return getBillingAgreementId(getContext());
	}

	/**
	 * @param context
	 * @return value of BillingAgreementId
	 */
	public final java.lang.String getBillingAgreementId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.BillingAgreementId.toString());
	}

	/**
	 * Set value of BillingAgreementId
	 * @param billingagreementid
	 */
	public final void setBillingAgreementId(java.lang.String billingagreementid)
	{
		setBillingAgreementId(getContext(), billingagreementid);
	}

	/**
	 * Set value of BillingAgreementId
	 * @param context
	 * @param billingagreementid
	 */
	public final void setBillingAgreementId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String billingagreementid)
	{
		getMendixObject().setValue(context, MemberNames.BillingAgreementId.toString(), billingagreementid);
	}

	/**
	 * @return value of PayPalDetails_Transaction
	 */
	public final braintreegateway.proxies.Transaction getPayPalDetails_Transaction() throws com.mendix.core.CoreException
	{
		return getPayPalDetails_Transaction(getContext());
	}

	/**
	 * @param context
	 * @return value of PayPalDetails_Transaction
	 */
	public final braintreegateway.proxies.Transaction getPayPalDetails_Transaction(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		braintreegateway.proxies.Transaction result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.PayPalDetails_Transaction.toString());
		if (identifier != null)
			result = braintreegateway.proxies.Transaction.load(context, identifier);
		return result;
	}

	/**
	 * Set value of PayPalDetails_Transaction
	 * @param paypaldetails_transaction
	 */
	public final void setPayPalDetails_Transaction(braintreegateway.proxies.Transaction paypaldetails_transaction)
	{
		setPayPalDetails_Transaction(getContext(), paypaldetails_transaction);
	}

	/**
	 * Set value of PayPalDetails_Transaction
	 * @param context
	 * @param paypaldetails_transaction
	 */
	public final void setPayPalDetails_Transaction(com.mendix.systemwideinterfaces.core.IContext context, braintreegateway.proxies.Transaction paypaldetails_transaction)
	{
		if (paypaldetails_transaction == null)
			getMendixObject().setValue(context, MemberNames.PayPalDetails_Transaction.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.PayPalDetails_Transaction.toString(), paypaldetails_transaction.getMendixObject().getId());
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final braintreegateway.proxies.PayPalDetails that = (braintreegateway.proxies.PayPalDetails) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "BraintreeGateway.PayPalDetails";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
