// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package braintreegateway.proxies;

public class RiskData
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject riskDataMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "BraintreeGateway.RiskData";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		_id("_id"),
		Decision("Decision"),
		DeviceDataCaptured("DeviceDataCaptured"),
		FraudServiceProvider("FraudServiceProvider"),
		RiskData_Transaction("BraintreeGateway.RiskData_Transaction");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public RiskData(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "BraintreeGateway.RiskData"));
	}

	protected RiskData(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject riskDataMendixObject)
	{
		if (riskDataMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("BraintreeGateway.RiskData", riskDataMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a BraintreeGateway.RiskData");

		this.riskDataMendixObject = riskDataMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'RiskData.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static braintreegateway.proxies.RiskData initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return braintreegateway.proxies.RiskData.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static braintreegateway.proxies.RiskData initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new braintreegateway.proxies.RiskData(context, mendixObject);
	}

	public static braintreegateway.proxies.RiskData load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return braintreegateway.proxies.RiskData.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of _id
	 */
	public final java.lang.String get_id()
	{
		return get_id(getContext());
	}

	/**
	 * @param context
	 * @return value of _id
	 */
	public final java.lang.String get_id(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._id.toString());
	}

	/**
	 * Set value of _id
	 * @param _id
	 */
	public final void set_id(java.lang.String _id)
	{
		set_id(getContext(), _id);
	}

	/**
	 * Set value of _id
	 * @param context
	 * @param _id
	 */
	public final void set_id(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _id)
	{
		getMendixObject().setValue(context, MemberNames._id.toString(), _id);
	}

	/**
	 * @return value of Decision
	 */
	public final java.lang.String getDecision()
	{
		return getDecision(getContext());
	}

	/**
	 * @param context
	 * @return value of Decision
	 */
	public final java.lang.String getDecision(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Decision.toString());
	}

	/**
	 * Set value of Decision
	 * @param decision
	 */
	public final void setDecision(java.lang.String decision)
	{
		setDecision(getContext(), decision);
	}

	/**
	 * Set value of Decision
	 * @param context
	 * @param decision
	 */
	public final void setDecision(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String decision)
	{
		getMendixObject().setValue(context, MemberNames.Decision.toString(), decision);
	}

	/**
	 * @return value of DeviceDataCaptured
	 */
	public final java.lang.Boolean getDeviceDataCaptured()
	{
		return getDeviceDataCaptured(getContext());
	}

	/**
	 * @param context
	 * @return value of DeviceDataCaptured
	 */
	public final java.lang.Boolean getDeviceDataCaptured(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.DeviceDataCaptured.toString());
	}

	/**
	 * Set value of DeviceDataCaptured
	 * @param devicedatacaptured
	 */
	public final void setDeviceDataCaptured(java.lang.Boolean devicedatacaptured)
	{
		setDeviceDataCaptured(getContext(), devicedatacaptured);
	}

	/**
	 * Set value of DeviceDataCaptured
	 * @param context
	 * @param devicedatacaptured
	 */
	public final void setDeviceDataCaptured(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean devicedatacaptured)
	{
		getMendixObject().setValue(context, MemberNames.DeviceDataCaptured.toString(), devicedatacaptured);
	}

	/**
	 * @return value of FraudServiceProvider
	 */
	public final java.lang.String getFraudServiceProvider()
	{
		return getFraudServiceProvider(getContext());
	}

	/**
	 * @param context
	 * @return value of FraudServiceProvider
	 */
	public final java.lang.String getFraudServiceProvider(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FraudServiceProvider.toString());
	}

	/**
	 * Set value of FraudServiceProvider
	 * @param fraudserviceprovider
	 */
	public final void setFraudServiceProvider(java.lang.String fraudserviceprovider)
	{
		setFraudServiceProvider(getContext(), fraudserviceprovider);
	}

	/**
	 * Set value of FraudServiceProvider
	 * @param context
	 * @param fraudserviceprovider
	 */
	public final void setFraudServiceProvider(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String fraudserviceprovider)
	{
		getMendixObject().setValue(context, MemberNames.FraudServiceProvider.toString(), fraudserviceprovider);
	}

	/**
	 * @return value of RiskData_Transaction
	 */
	public final braintreegateway.proxies.Transaction getRiskData_Transaction() throws com.mendix.core.CoreException
	{
		return getRiskData_Transaction(getContext());
	}

	/**
	 * @param context
	 * @return value of RiskData_Transaction
	 */
	public final braintreegateway.proxies.Transaction getRiskData_Transaction(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		braintreegateway.proxies.Transaction result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.RiskData_Transaction.toString());
		if (identifier != null)
			result = braintreegateway.proxies.Transaction.load(context, identifier);
		return result;
	}

	/**
	 * Set value of RiskData_Transaction
	 * @param riskdata_transaction
	 */
	public final void setRiskData_Transaction(braintreegateway.proxies.Transaction riskdata_transaction)
	{
		setRiskData_Transaction(getContext(), riskdata_transaction);
	}

	/**
	 * Set value of RiskData_Transaction
	 * @param context
	 * @param riskdata_transaction
	 */
	public final void setRiskData_Transaction(com.mendix.systemwideinterfaces.core.IContext context, braintreegateway.proxies.Transaction riskdata_transaction)
	{
		if (riskdata_transaction == null)
			getMendixObject().setValue(context, MemberNames.RiskData_Transaction.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.RiskData_Transaction.toString(), riskdata_transaction.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return riskDataMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final braintreegateway.proxies.RiskData that = (braintreegateway.proxies.RiskData) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "BraintreeGateway.RiskData";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
