// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package braintreegateway.proxies;

public class ShippingAddress extends braintreegateway.proxies.Address
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "BraintreeGateway.ShippingAddress";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Company("Company"),
		CountryCodeAlpha2("CountryCodeAlpha2"),
		CountryCodeAlpha3("CountryCodeAlpha3"),
		CountryCodeNumeric("CountryCodeNumeric"),
		CountryName("CountryName"),
		CreatedAt("CreatedAt"),
		CustomerId("CustomerId"),
		ExtendedAddress("ExtendedAddress"),
		FirstName("FirstName"),
		_id("_id"),
		LastName("LastName"),
		Locality("Locality"),
		PostalCode("PostalCode"),
		Region("Region"),
		RecipientName("RecipientName"),
		StreetAddress("StreetAddress"),
		UpdatedAt("UpdatedAt"),
		ShippingAddress_Transaction("BraintreeGateway.ShippingAddress_Transaction");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ShippingAddress(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "BraintreeGateway.ShippingAddress"));
	}

	protected ShippingAddress(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject shippingAddressMendixObject)
	{
		super(context, shippingAddressMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("BraintreeGateway.ShippingAddress", shippingAddressMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a BraintreeGateway.ShippingAddress");
	}

	/**
	 * @deprecated Use 'ShippingAddress.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static braintreegateway.proxies.ShippingAddress initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return braintreegateway.proxies.ShippingAddress.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static braintreegateway.proxies.ShippingAddress initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new braintreegateway.proxies.ShippingAddress(context, mendixObject);
	}

	public static braintreegateway.proxies.ShippingAddress load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return braintreegateway.proxies.ShippingAddress.initialize(context, mendixObject);
	}

	/**
	 * @return value of ShippingAddress_Transaction
	 */
	public final braintreegateway.proxies.Transaction getShippingAddress_Transaction() throws com.mendix.core.CoreException
	{
		return getShippingAddress_Transaction(getContext());
	}

	/**
	 * @param context
	 * @return value of ShippingAddress_Transaction
	 */
	public final braintreegateway.proxies.Transaction getShippingAddress_Transaction(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		braintreegateway.proxies.Transaction result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ShippingAddress_Transaction.toString());
		if (identifier != null)
			result = braintreegateway.proxies.Transaction.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ShippingAddress_Transaction
	 * @param shippingaddress_transaction
	 */
	public final void setShippingAddress_Transaction(braintreegateway.proxies.Transaction shippingaddress_transaction)
	{
		setShippingAddress_Transaction(getContext(), shippingaddress_transaction);
	}

	/**
	 * Set value of ShippingAddress_Transaction
	 * @param context
	 * @param shippingaddress_transaction
	 */
	public final void setShippingAddress_Transaction(com.mendix.systemwideinterfaces.core.IContext context, braintreegateway.proxies.Transaction shippingaddress_transaction)
	{
		if (shippingaddress_transaction == null)
			getMendixObject().setValue(context, MemberNames.ShippingAddress_Transaction.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ShippingAddress_Transaction.toString(), shippingaddress_transaction.getMendixObject().getId());
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final braintreegateway.proxies.ShippingAddress that = (braintreegateway.proxies.ShippingAddress) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "BraintreeGateway.ShippingAddress";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
