// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package braintreegateway.proxies;

public class SubscriptionDetails
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject subscriptionDetailsMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "BraintreeGateway.SubscriptionDetails";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		BillingPeriodEndDate("BillingPeriodEndDate"),
		BillingPeriodStartDate("BillingPeriodStartDate"),
		SubscriptionDetails_Transaction("BraintreeGateway.SubscriptionDetails_Transaction");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public SubscriptionDetails(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "BraintreeGateway.SubscriptionDetails"));
	}

	protected SubscriptionDetails(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject subscriptionDetailsMendixObject)
	{
		if (subscriptionDetailsMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("BraintreeGateway.SubscriptionDetails", subscriptionDetailsMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a BraintreeGateway.SubscriptionDetails");

		this.subscriptionDetailsMendixObject = subscriptionDetailsMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'SubscriptionDetails.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static braintreegateway.proxies.SubscriptionDetails initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return braintreegateway.proxies.SubscriptionDetails.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static braintreegateway.proxies.SubscriptionDetails initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new braintreegateway.proxies.SubscriptionDetails(context, mendixObject);
	}

	public static braintreegateway.proxies.SubscriptionDetails load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return braintreegateway.proxies.SubscriptionDetails.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of BillingPeriodEndDate
	 */
	public final java.lang.String getBillingPeriodEndDate()
	{
		return getBillingPeriodEndDate(getContext());
	}

	/**
	 * @param context
	 * @return value of BillingPeriodEndDate
	 */
	public final java.lang.String getBillingPeriodEndDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.BillingPeriodEndDate.toString());
	}

	/**
	 * Set value of BillingPeriodEndDate
	 * @param billingperiodenddate
	 */
	public final void setBillingPeriodEndDate(java.lang.String billingperiodenddate)
	{
		setBillingPeriodEndDate(getContext(), billingperiodenddate);
	}

	/**
	 * Set value of BillingPeriodEndDate
	 * @param context
	 * @param billingperiodenddate
	 */
	public final void setBillingPeriodEndDate(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String billingperiodenddate)
	{
		getMendixObject().setValue(context, MemberNames.BillingPeriodEndDate.toString(), billingperiodenddate);
	}

	/**
	 * @return value of BillingPeriodStartDate
	 */
	public final java.lang.String getBillingPeriodStartDate()
	{
		return getBillingPeriodStartDate(getContext());
	}

	/**
	 * @param context
	 * @return value of BillingPeriodStartDate
	 */
	public final java.lang.String getBillingPeriodStartDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.BillingPeriodStartDate.toString());
	}

	/**
	 * Set value of BillingPeriodStartDate
	 * @param billingperiodstartdate
	 */
	public final void setBillingPeriodStartDate(java.lang.String billingperiodstartdate)
	{
		setBillingPeriodStartDate(getContext(), billingperiodstartdate);
	}

	/**
	 * Set value of BillingPeriodStartDate
	 * @param context
	 * @param billingperiodstartdate
	 */
	public final void setBillingPeriodStartDate(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String billingperiodstartdate)
	{
		getMendixObject().setValue(context, MemberNames.BillingPeriodStartDate.toString(), billingperiodstartdate);
	}

	/**
	 * @return value of SubscriptionDetails_Transaction
	 */
	public final braintreegateway.proxies.Transaction getSubscriptionDetails_Transaction() throws com.mendix.core.CoreException
	{
		return getSubscriptionDetails_Transaction(getContext());
	}

	/**
	 * @param context
	 * @return value of SubscriptionDetails_Transaction
	 */
	public final braintreegateway.proxies.Transaction getSubscriptionDetails_Transaction(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		braintreegateway.proxies.Transaction result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SubscriptionDetails_Transaction.toString());
		if (identifier != null)
			result = braintreegateway.proxies.Transaction.load(context, identifier);
		return result;
	}

	/**
	 * Set value of SubscriptionDetails_Transaction
	 * @param subscriptiondetails_transaction
	 */
	public final void setSubscriptionDetails_Transaction(braintreegateway.proxies.Transaction subscriptiondetails_transaction)
	{
		setSubscriptionDetails_Transaction(getContext(), subscriptiondetails_transaction);
	}

	/**
	 * Set value of SubscriptionDetails_Transaction
	 * @param context
	 * @param subscriptiondetails_transaction
	 */
	public final void setSubscriptionDetails_Transaction(com.mendix.systemwideinterfaces.core.IContext context, braintreegateway.proxies.Transaction subscriptiondetails_transaction)
	{
		if (subscriptiondetails_transaction == null)
			getMendixObject().setValue(context, MemberNames.SubscriptionDetails_Transaction.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.SubscriptionDetails_Transaction.toString(), subscriptiondetails_transaction.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return subscriptionDetailsMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final braintreegateway.proxies.SubscriptionDetails that = (braintreegateway.proxies.SubscriptionDetails) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "BraintreeGateway.SubscriptionDetails";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
