// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package braintreegateway.proxies;

public class Transaction
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject transactionMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "BraintreeGateway.Transaction";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		RawJSON("RawJSON"),
		Amount("Amount"),
		AvsErrorResponseCode("AvsErrorResponseCode"),
		AvsPostalCodeResponseCode("AvsPostalCodeResponseCode"),
		AvsStreetAddressResponseCode("AvsStreetAddressResponseCode"),
		Channel("Channel"),
		CreatedAt("CreatedAt"),
		CurrencyIsoCode("CurrencyIsoCode"),
		CvvResponseCode("CvvResponseCode"),
		EscrowStatus("EscrowStatus"),
		GatewayRejectionReason("GatewayRejectionReason"),
		_id("_id"),
		MerchantAccountId("MerchantAccountId"),
		OrderId("OrderId"),
		PlanId("PlanId"),
		ProcessedWithNetworkToken("ProcessedWithNetworkToken"),
		ProcessorAuthorizationCode("ProcessorAuthorizationCode"),
		ProcessorResponseCode("ProcessorResponseCode"),
		ProcessorResponseText("ProcessorResponseText"),
		ProcessorResponseType("ProcessorResponseType"),
		ProcessorSettlementResponseCode("ProcessorSettlementResponseCode"),
		ProcessorSettlementResponseText("ProcessorSettlementResponseText"),
		AdditionalProcessorResponse("AdditionalProcessorResponse"),
		NetworkResponseCode("NetworkResponseCode"),
		NetworkResponseText("NetworkResponseText"),
		VoiceReferralNumber("VoiceReferralNumber"),
		PurchaseOrderNumber("PurchaseOrderNumber"),
		Recurring("Recurring"),
		RefundedTransactionId("RefundedTransactionId"),
		RetrievalReferenceNumber("RetrievalReferenceNumber"),
		AcquirerReferenceNumber("AcquirerReferenceNumber"),
		SettlementBatchId("SettlementBatchId"),
		Status("Status"),
		SubscriptionId("SubscriptionId"),
		TaxAmount("TaxAmount"),
		TaxExempt("TaxExempt"),
		ShippingAmount("ShippingAmount"),
		DiscountAmount("DiscountAmount"),
		ShipsFromPostalCode("ShipsFromPostalCode"),
		_type("_type"),
		UpdatedAt("UpdatedAt"),
		ServiceFeeAmount("ServiceFeeAmount"),
		PaymentInstrumentType("PaymentInstrumentType"),
		AuthorizedTransactionId("AuthorizedTransactionId"),
		NetworkTransactionId("NetworkTransactionId"),
		ScaExemptionRequested("ScaExemptionRequested"),
		AuthorizationExpiresAt("AuthorizationExpiresAt"),
		InstallmentCount("InstallmentCount"),
		Disbursed("Disbursed"),
		GraphQLId("GraphQLId"),
		BillingAddress_Transaction("BraintreeGateway.BillingAddress_Transaction"),
		CreditCard_Transaction("BraintreeGateway.CreditCard_Transaction"),
		DisbursementDetails_Transaction("BraintreeGateway.DisbursementDetails_Transaction"),
		Descriptor_Transaction("BraintreeGateway.Descriptor_Transaction"),
		ApplePayDetails_Transaction("BraintreeGateway.ApplePayDetails_Transaction"),
		AndroidPayDetails_Transaction("BraintreeGateway.AndroidPayDetails_Transaction"),
		ShippingAddress_Transaction("BraintreeGateway.ShippingAddress_Transaction"),
		SubscriptionDetails_Transaction("BraintreeGateway.SubscriptionDetails_Transaction"),
		RiskData_Transaction("BraintreeGateway.RiskData_Transaction"),
		PayPalDetails_Transaction("BraintreeGateway.PayPalDetails_Transaction"),
		ThreeDSecureInfo_Transaction("BraintreeGateway.ThreeDSecureInfo_Transaction");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Transaction(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "BraintreeGateway.Transaction"));
	}

	protected Transaction(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject transactionMendixObject)
	{
		if (transactionMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("BraintreeGateway.Transaction", transactionMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a BraintreeGateway.Transaction");

		this.transactionMendixObject = transactionMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Transaction.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static braintreegateway.proxies.Transaction initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return braintreegateway.proxies.Transaction.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static braintreegateway.proxies.Transaction initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new braintreegateway.proxies.Transaction(context, mendixObject);
	}

	public static braintreegateway.proxies.Transaction load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return braintreegateway.proxies.Transaction.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of RawJSON
	 */
	public final java.lang.String getRawJSON()
	{
		return getRawJSON(getContext());
	}

	/**
	 * @param context
	 * @return value of RawJSON
	 */
	public final java.lang.String getRawJSON(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.RawJSON.toString());
	}

	/**
	 * Set value of RawJSON
	 * @param rawjson
	 */
	public final void setRawJSON(java.lang.String rawjson)
	{
		setRawJSON(getContext(), rawjson);
	}

	/**
	 * Set value of RawJSON
	 * @param context
	 * @param rawjson
	 */
	public final void setRawJSON(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String rawjson)
	{
		getMendixObject().setValue(context, MemberNames.RawJSON.toString(), rawjson);
	}

	/**
	 * @return value of Amount
	 */
	public final java.math.BigDecimal getAmount()
	{
		return getAmount(getContext());
	}

	/**
	 * @param context
	 * @return value of Amount
	 */
	public final java.math.BigDecimal getAmount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Amount.toString());
	}

	/**
	 * Set value of Amount
	 * @param amount
	 */
	public final void setAmount(java.math.BigDecimal amount)
	{
		setAmount(getContext(), amount);
	}

	/**
	 * Set value of Amount
	 * @param context
	 * @param amount
	 */
	public final void setAmount(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal amount)
	{
		getMendixObject().setValue(context, MemberNames.Amount.toString(), amount);
	}

	/**
	 * @return value of AvsErrorResponseCode
	 */
	public final java.lang.String getAvsErrorResponseCode()
	{
		return getAvsErrorResponseCode(getContext());
	}

	/**
	 * @param context
	 * @return value of AvsErrorResponseCode
	 */
	public final java.lang.String getAvsErrorResponseCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AvsErrorResponseCode.toString());
	}

	/**
	 * Set value of AvsErrorResponseCode
	 * @param avserrorresponsecode
	 */
	public final void setAvsErrorResponseCode(java.lang.String avserrorresponsecode)
	{
		setAvsErrorResponseCode(getContext(), avserrorresponsecode);
	}

	/**
	 * Set value of AvsErrorResponseCode
	 * @param context
	 * @param avserrorresponsecode
	 */
	public final void setAvsErrorResponseCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String avserrorresponsecode)
	{
		getMendixObject().setValue(context, MemberNames.AvsErrorResponseCode.toString(), avserrorresponsecode);
	}

	/**
	 * @return value of AvsPostalCodeResponseCode
	 */
	public final java.lang.String getAvsPostalCodeResponseCode()
	{
		return getAvsPostalCodeResponseCode(getContext());
	}

	/**
	 * @param context
	 * @return value of AvsPostalCodeResponseCode
	 */
	public final java.lang.String getAvsPostalCodeResponseCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AvsPostalCodeResponseCode.toString());
	}

	/**
	 * Set value of AvsPostalCodeResponseCode
	 * @param avspostalcoderesponsecode
	 */
	public final void setAvsPostalCodeResponseCode(java.lang.String avspostalcoderesponsecode)
	{
		setAvsPostalCodeResponseCode(getContext(), avspostalcoderesponsecode);
	}

	/**
	 * Set value of AvsPostalCodeResponseCode
	 * @param context
	 * @param avspostalcoderesponsecode
	 */
	public final void setAvsPostalCodeResponseCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String avspostalcoderesponsecode)
	{
		getMendixObject().setValue(context, MemberNames.AvsPostalCodeResponseCode.toString(), avspostalcoderesponsecode);
	}

	/**
	 * @return value of AvsStreetAddressResponseCode
	 */
	public final java.lang.String getAvsStreetAddressResponseCode()
	{
		return getAvsStreetAddressResponseCode(getContext());
	}

	/**
	 * @param context
	 * @return value of AvsStreetAddressResponseCode
	 */
	public final java.lang.String getAvsStreetAddressResponseCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AvsStreetAddressResponseCode.toString());
	}

	/**
	 * Set value of AvsStreetAddressResponseCode
	 * @param avsstreetaddressresponsecode
	 */
	public final void setAvsStreetAddressResponseCode(java.lang.String avsstreetaddressresponsecode)
	{
		setAvsStreetAddressResponseCode(getContext(), avsstreetaddressresponsecode);
	}

	/**
	 * Set value of AvsStreetAddressResponseCode
	 * @param context
	 * @param avsstreetaddressresponsecode
	 */
	public final void setAvsStreetAddressResponseCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String avsstreetaddressresponsecode)
	{
		getMendixObject().setValue(context, MemberNames.AvsStreetAddressResponseCode.toString(), avsstreetaddressresponsecode);
	}

	/**
	 * @return value of Channel
	 */
	public final java.lang.String getChannel()
	{
		return getChannel(getContext());
	}

	/**
	 * @param context
	 * @return value of Channel
	 */
	public final java.lang.String getChannel(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Channel.toString());
	}

	/**
	 * Set value of Channel
	 * @param channel
	 */
	public final void setChannel(java.lang.String channel)
	{
		setChannel(getContext(), channel);
	}

	/**
	 * Set value of Channel
	 * @param context
	 * @param channel
	 */
	public final void setChannel(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String channel)
	{
		getMendixObject().setValue(context, MemberNames.Channel.toString(), channel);
	}

	/**
	 * @return value of CreatedAt
	 */
	public final java.lang.Long getCreatedAt()
	{
		return getCreatedAt(getContext());
	}

	/**
	 * @param context
	 * @return value of CreatedAt
	 */
	public final java.lang.Long getCreatedAt(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.CreatedAt.toString());
	}

	/**
	 * Set value of CreatedAt
	 * @param createdat
	 */
	public final void setCreatedAt(java.lang.Long createdat)
	{
		setCreatedAt(getContext(), createdat);
	}

	/**
	 * Set value of CreatedAt
	 * @param context
	 * @param createdat
	 */
	public final void setCreatedAt(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long createdat)
	{
		getMendixObject().setValue(context, MemberNames.CreatedAt.toString(), createdat);
	}

	/**
	 * @return value of CurrencyIsoCode
	 */
	public final java.lang.String getCurrencyIsoCode()
	{
		return getCurrencyIsoCode(getContext());
	}

	/**
	 * @param context
	 * @return value of CurrencyIsoCode
	 */
	public final java.lang.String getCurrencyIsoCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CurrencyIsoCode.toString());
	}

	/**
	 * Set value of CurrencyIsoCode
	 * @param currencyisocode
	 */
	public final void setCurrencyIsoCode(java.lang.String currencyisocode)
	{
		setCurrencyIsoCode(getContext(), currencyisocode);
	}

	/**
	 * Set value of CurrencyIsoCode
	 * @param context
	 * @param currencyisocode
	 */
	public final void setCurrencyIsoCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String currencyisocode)
	{
		getMendixObject().setValue(context, MemberNames.CurrencyIsoCode.toString(), currencyisocode);
	}

	/**
	 * @return value of CvvResponseCode
	 */
	public final java.lang.String getCvvResponseCode()
	{
		return getCvvResponseCode(getContext());
	}

	/**
	 * @param context
	 * @return value of CvvResponseCode
	 */
	public final java.lang.String getCvvResponseCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CvvResponseCode.toString());
	}

	/**
	 * Set value of CvvResponseCode
	 * @param cvvresponsecode
	 */
	public final void setCvvResponseCode(java.lang.String cvvresponsecode)
	{
		setCvvResponseCode(getContext(), cvvresponsecode);
	}

	/**
	 * Set value of CvvResponseCode
	 * @param context
	 * @param cvvresponsecode
	 */
	public final void setCvvResponseCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String cvvresponsecode)
	{
		getMendixObject().setValue(context, MemberNames.CvvResponseCode.toString(), cvvresponsecode);
	}

	/**
	 * @return value of EscrowStatus
	 */
	public final java.lang.String getEscrowStatus()
	{
		return getEscrowStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of EscrowStatus
	 */
	public final java.lang.String getEscrowStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EscrowStatus.toString());
	}

	/**
	 * Set value of EscrowStatus
	 * @param escrowstatus
	 */
	public final void setEscrowStatus(java.lang.String escrowstatus)
	{
		setEscrowStatus(getContext(), escrowstatus);
	}

	/**
	 * Set value of EscrowStatus
	 * @param context
	 * @param escrowstatus
	 */
	public final void setEscrowStatus(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String escrowstatus)
	{
		getMendixObject().setValue(context, MemberNames.EscrowStatus.toString(), escrowstatus);
	}

	/**
	 * @return value of GatewayRejectionReason
	 */
	public final java.lang.String getGatewayRejectionReason()
	{
		return getGatewayRejectionReason(getContext());
	}

	/**
	 * @param context
	 * @return value of GatewayRejectionReason
	 */
	public final java.lang.String getGatewayRejectionReason(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.GatewayRejectionReason.toString());
	}

	/**
	 * Set value of GatewayRejectionReason
	 * @param gatewayrejectionreason
	 */
	public final void setGatewayRejectionReason(java.lang.String gatewayrejectionreason)
	{
		setGatewayRejectionReason(getContext(), gatewayrejectionreason);
	}

	/**
	 * Set value of GatewayRejectionReason
	 * @param context
	 * @param gatewayrejectionreason
	 */
	public final void setGatewayRejectionReason(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String gatewayrejectionreason)
	{
		getMendixObject().setValue(context, MemberNames.GatewayRejectionReason.toString(), gatewayrejectionreason);
	}

	/**
	 * @return value of _id
	 */
	public final java.lang.String get_id()
	{
		return get_id(getContext());
	}

	/**
	 * @param context
	 * @return value of _id
	 */
	public final java.lang.String get_id(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._id.toString());
	}

	/**
	 * Set value of _id
	 * @param _id
	 */
	public final void set_id(java.lang.String _id)
	{
		set_id(getContext(), _id);
	}

	/**
	 * Set value of _id
	 * @param context
	 * @param _id
	 */
	public final void set_id(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _id)
	{
		getMendixObject().setValue(context, MemberNames._id.toString(), _id);
	}

	/**
	 * @return value of MerchantAccountId
	 */
	public final java.lang.String getMerchantAccountId()
	{
		return getMerchantAccountId(getContext());
	}

	/**
	 * @param context
	 * @return value of MerchantAccountId
	 */
	public final java.lang.String getMerchantAccountId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MerchantAccountId.toString());
	}

	/**
	 * Set value of MerchantAccountId
	 * @param merchantaccountid
	 */
	public final void setMerchantAccountId(java.lang.String merchantaccountid)
	{
		setMerchantAccountId(getContext(), merchantaccountid);
	}

	/**
	 * Set value of MerchantAccountId
	 * @param context
	 * @param merchantaccountid
	 */
	public final void setMerchantAccountId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String merchantaccountid)
	{
		getMendixObject().setValue(context, MemberNames.MerchantAccountId.toString(), merchantaccountid);
	}

	/**
	 * @return value of OrderId
	 */
	public final java.lang.String getOrderId()
	{
		return getOrderId(getContext());
	}

	/**
	 * @param context
	 * @return value of OrderId
	 */
	public final java.lang.String getOrderId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OrderId.toString());
	}

	/**
	 * Set value of OrderId
	 * @param orderid
	 */
	public final void setOrderId(java.lang.String orderid)
	{
		setOrderId(getContext(), orderid);
	}

	/**
	 * Set value of OrderId
	 * @param context
	 * @param orderid
	 */
	public final void setOrderId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String orderid)
	{
		getMendixObject().setValue(context, MemberNames.OrderId.toString(), orderid);
	}

	/**
	 * @return value of PlanId
	 */
	public final java.lang.String getPlanId()
	{
		return getPlanId(getContext());
	}

	/**
	 * @param context
	 * @return value of PlanId
	 */
	public final java.lang.String getPlanId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PlanId.toString());
	}

	/**
	 * Set value of PlanId
	 * @param planid
	 */
	public final void setPlanId(java.lang.String planid)
	{
		setPlanId(getContext(), planid);
	}

	/**
	 * Set value of PlanId
	 * @param context
	 * @param planid
	 */
	public final void setPlanId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String planid)
	{
		getMendixObject().setValue(context, MemberNames.PlanId.toString(), planid);
	}

	/**
	 * @return value of ProcessedWithNetworkToken
	 */
	public final java.lang.Boolean getProcessedWithNetworkToken()
	{
		return getProcessedWithNetworkToken(getContext());
	}

	/**
	 * @param context
	 * @return value of ProcessedWithNetworkToken
	 */
	public final java.lang.Boolean getProcessedWithNetworkToken(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ProcessedWithNetworkToken.toString());
	}

	/**
	 * Set value of ProcessedWithNetworkToken
	 * @param processedwithnetworktoken
	 */
	public final void setProcessedWithNetworkToken(java.lang.Boolean processedwithnetworktoken)
	{
		setProcessedWithNetworkToken(getContext(), processedwithnetworktoken);
	}

	/**
	 * Set value of ProcessedWithNetworkToken
	 * @param context
	 * @param processedwithnetworktoken
	 */
	public final void setProcessedWithNetworkToken(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean processedwithnetworktoken)
	{
		getMendixObject().setValue(context, MemberNames.ProcessedWithNetworkToken.toString(), processedwithnetworktoken);
	}

	/**
	 * @return value of ProcessorAuthorizationCode
	 */
	public final java.lang.String getProcessorAuthorizationCode()
	{
		return getProcessorAuthorizationCode(getContext());
	}

	/**
	 * @param context
	 * @return value of ProcessorAuthorizationCode
	 */
	public final java.lang.String getProcessorAuthorizationCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ProcessorAuthorizationCode.toString());
	}

	/**
	 * Set value of ProcessorAuthorizationCode
	 * @param processorauthorizationcode
	 */
	public final void setProcessorAuthorizationCode(java.lang.String processorauthorizationcode)
	{
		setProcessorAuthorizationCode(getContext(), processorauthorizationcode);
	}

	/**
	 * Set value of ProcessorAuthorizationCode
	 * @param context
	 * @param processorauthorizationcode
	 */
	public final void setProcessorAuthorizationCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String processorauthorizationcode)
	{
		getMendixObject().setValue(context, MemberNames.ProcessorAuthorizationCode.toString(), processorauthorizationcode);
	}

	/**
	 * @return value of ProcessorResponseCode
	 */
	public final java.lang.String getProcessorResponseCode()
	{
		return getProcessorResponseCode(getContext());
	}

	/**
	 * @param context
	 * @return value of ProcessorResponseCode
	 */
	public final java.lang.String getProcessorResponseCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ProcessorResponseCode.toString());
	}

	/**
	 * Set value of ProcessorResponseCode
	 * @param processorresponsecode
	 */
	public final void setProcessorResponseCode(java.lang.String processorresponsecode)
	{
		setProcessorResponseCode(getContext(), processorresponsecode);
	}

	/**
	 * Set value of ProcessorResponseCode
	 * @param context
	 * @param processorresponsecode
	 */
	public final void setProcessorResponseCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String processorresponsecode)
	{
		getMendixObject().setValue(context, MemberNames.ProcessorResponseCode.toString(), processorresponsecode);
	}

	/**
	 * @return value of ProcessorResponseText
	 */
	public final java.lang.String getProcessorResponseText()
	{
		return getProcessorResponseText(getContext());
	}

	/**
	 * @param context
	 * @return value of ProcessorResponseText
	 */
	public final java.lang.String getProcessorResponseText(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ProcessorResponseText.toString());
	}

	/**
	 * Set value of ProcessorResponseText
	 * @param processorresponsetext
	 */
	public final void setProcessorResponseText(java.lang.String processorresponsetext)
	{
		setProcessorResponseText(getContext(), processorresponsetext);
	}

	/**
	 * Set value of ProcessorResponseText
	 * @param context
	 * @param processorresponsetext
	 */
	public final void setProcessorResponseText(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String processorresponsetext)
	{
		getMendixObject().setValue(context, MemberNames.ProcessorResponseText.toString(), processorresponsetext);
	}

	/**
	 * @return value of ProcessorResponseType
	 */
	public final java.lang.String getProcessorResponseType()
	{
		return getProcessorResponseType(getContext());
	}

	/**
	 * @param context
	 * @return value of ProcessorResponseType
	 */
	public final java.lang.String getProcessorResponseType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ProcessorResponseType.toString());
	}

	/**
	 * Set value of ProcessorResponseType
	 * @param processorresponsetype
	 */
	public final void setProcessorResponseType(java.lang.String processorresponsetype)
	{
		setProcessorResponseType(getContext(), processorresponsetype);
	}

	/**
	 * Set value of ProcessorResponseType
	 * @param context
	 * @param processorresponsetype
	 */
	public final void setProcessorResponseType(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String processorresponsetype)
	{
		getMendixObject().setValue(context, MemberNames.ProcessorResponseType.toString(), processorresponsetype);
	}

	/**
	 * @return value of ProcessorSettlementResponseCode
	 */
	public final java.lang.String getProcessorSettlementResponseCode()
	{
		return getProcessorSettlementResponseCode(getContext());
	}

	/**
	 * @param context
	 * @return value of ProcessorSettlementResponseCode
	 */
	public final java.lang.String getProcessorSettlementResponseCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ProcessorSettlementResponseCode.toString());
	}

	/**
	 * Set value of ProcessorSettlementResponseCode
	 * @param processorsettlementresponsecode
	 */
	public final void setProcessorSettlementResponseCode(java.lang.String processorsettlementresponsecode)
	{
		setProcessorSettlementResponseCode(getContext(), processorsettlementresponsecode);
	}

	/**
	 * Set value of ProcessorSettlementResponseCode
	 * @param context
	 * @param processorsettlementresponsecode
	 */
	public final void setProcessorSettlementResponseCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String processorsettlementresponsecode)
	{
		getMendixObject().setValue(context, MemberNames.ProcessorSettlementResponseCode.toString(), processorsettlementresponsecode);
	}

	/**
	 * @return value of ProcessorSettlementResponseText
	 */
	public final java.lang.String getProcessorSettlementResponseText()
	{
		return getProcessorSettlementResponseText(getContext());
	}

	/**
	 * @param context
	 * @return value of ProcessorSettlementResponseText
	 */
	public final java.lang.String getProcessorSettlementResponseText(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ProcessorSettlementResponseText.toString());
	}

	/**
	 * Set value of ProcessorSettlementResponseText
	 * @param processorsettlementresponsetext
	 */
	public final void setProcessorSettlementResponseText(java.lang.String processorsettlementresponsetext)
	{
		setProcessorSettlementResponseText(getContext(), processorsettlementresponsetext);
	}

	/**
	 * Set value of ProcessorSettlementResponseText
	 * @param context
	 * @param processorsettlementresponsetext
	 */
	public final void setProcessorSettlementResponseText(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String processorsettlementresponsetext)
	{
		getMendixObject().setValue(context, MemberNames.ProcessorSettlementResponseText.toString(), processorsettlementresponsetext);
	}

	/**
	 * @return value of AdditionalProcessorResponse
	 */
	public final java.lang.String getAdditionalProcessorResponse()
	{
		return getAdditionalProcessorResponse(getContext());
	}

	/**
	 * @param context
	 * @return value of AdditionalProcessorResponse
	 */
	public final java.lang.String getAdditionalProcessorResponse(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AdditionalProcessorResponse.toString());
	}

	/**
	 * Set value of AdditionalProcessorResponse
	 * @param additionalprocessorresponse
	 */
	public final void setAdditionalProcessorResponse(java.lang.String additionalprocessorresponse)
	{
		setAdditionalProcessorResponse(getContext(), additionalprocessorresponse);
	}

	/**
	 * Set value of AdditionalProcessorResponse
	 * @param context
	 * @param additionalprocessorresponse
	 */
	public final void setAdditionalProcessorResponse(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String additionalprocessorresponse)
	{
		getMendixObject().setValue(context, MemberNames.AdditionalProcessorResponse.toString(), additionalprocessorresponse);
	}

	/**
	 * @return value of NetworkResponseCode
	 */
	public final java.lang.String getNetworkResponseCode()
	{
		return getNetworkResponseCode(getContext());
	}

	/**
	 * @param context
	 * @return value of NetworkResponseCode
	 */
	public final java.lang.String getNetworkResponseCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.NetworkResponseCode.toString());
	}

	/**
	 * Set value of NetworkResponseCode
	 * @param networkresponsecode
	 */
	public final void setNetworkResponseCode(java.lang.String networkresponsecode)
	{
		setNetworkResponseCode(getContext(), networkresponsecode);
	}

	/**
	 * Set value of NetworkResponseCode
	 * @param context
	 * @param networkresponsecode
	 */
	public final void setNetworkResponseCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String networkresponsecode)
	{
		getMendixObject().setValue(context, MemberNames.NetworkResponseCode.toString(), networkresponsecode);
	}

	/**
	 * @return value of NetworkResponseText
	 */
	public final java.lang.String getNetworkResponseText()
	{
		return getNetworkResponseText(getContext());
	}

	/**
	 * @param context
	 * @return value of NetworkResponseText
	 */
	public final java.lang.String getNetworkResponseText(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.NetworkResponseText.toString());
	}

	/**
	 * Set value of NetworkResponseText
	 * @param networkresponsetext
	 */
	public final void setNetworkResponseText(java.lang.String networkresponsetext)
	{
		setNetworkResponseText(getContext(), networkresponsetext);
	}

	/**
	 * Set value of NetworkResponseText
	 * @param context
	 * @param networkresponsetext
	 */
	public final void setNetworkResponseText(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String networkresponsetext)
	{
		getMendixObject().setValue(context, MemberNames.NetworkResponseText.toString(), networkresponsetext);
	}

	/**
	 * @return value of VoiceReferralNumber
	 */
	public final java.lang.String getVoiceReferralNumber()
	{
		return getVoiceReferralNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of VoiceReferralNumber
	 */
	public final java.lang.String getVoiceReferralNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.VoiceReferralNumber.toString());
	}

	/**
	 * Set value of VoiceReferralNumber
	 * @param voicereferralnumber
	 */
	public final void setVoiceReferralNumber(java.lang.String voicereferralnumber)
	{
		setVoiceReferralNumber(getContext(), voicereferralnumber);
	}

	/**
	 * Set value of VoiceReferralNumber
	 * @param context
	 * @param voicereferralnumber
	 */
	public final void setVoiceReferralNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String voicereferralnumber)
	{
		getMendixObject().setValue(context, MemberNames.VoiceReferralNumber.toString(), voicereferralnumber);
	}

	/**
	 * @return value of PurchaseOrderNumber
	 */
	public final java.lang.String getPurchaseOrderNumber()
	{
		return getPurchaseOrderNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of PurchaseOrderNumber
	 */
	public final java.lang.String getPurchaseOrderNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PurchaseOrderNumber.toString());
	}

	/**
	 * Set value of PurchaseOrderNumber
	 * @param purchaseordernumber
	 */
	public final void setPurchaseOrderNumber(java.lang.String purchaseordernumber)
	{
		setPurchaseOrderNumber(getContext(), purchaseordernumber);
	}

	/**
	 * Set value of PurchaseOrderNumber
	 * @param context
	 * @param purchaseordernumber
	 */
	public final void setPurchaseOrderNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String purchaseordernumber)
	{
		getMendixObject().setValue(context, MemberNames.PurchaseOrderNumber.toString(), purchaseordernumber);
	}

	/**
	 * @return value of Recurring
	 */
	public final java.lang.Boolean getRecurring()
	{
		return getRecurring(getContext());
	}

	/**
	 * @param context
	 * @return value of Recurring
	 */
	public final java.lang.Boolean getRecurring(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Recurring.toString());
	}

	/**
	 * Set value of Recurring
	 * @param recurring
	 */
	public final void setRecurring(java.lang.Boolean recurring)
	{
		setRecurring(getContext(), recurring);
	}

	/**
	 * Set value of Recurring
	 * @param context
	 * @param recurring
	 */
	public final void setRecurring(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean recurring)
	{
		getMendixObject().setValue(context, MemberNames.Recurring.toString(), recurring);
	}

	/**
	 * @return value of RefundedTransactionId
	 */
	public final java.lang.String getRefundedTransactionId()
	{
		return getRefundedTransactionId(getContext());
	}

	/**
	 * @param context
	 * @return value of RefundedTransactionId
	 */
	public final java.lang.String getRefundedTransactionId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.RefundedTransactionId.toString());
	}

	/**
	 * Set value of RefundedTransactionId
	 * @param refundedtransactionid
	 */
	public final void setRefundedTransactionId(java.lang.String refundedtransactionid)
	{
		setRefundedTransactionId(getContext(), refundedtransactionid);
	}

	/**
	 * Set value of RefundedTransactionId
	 * @param context
	 * @param refundedtransactionid
	 */
	public final void setRefundedTransactionId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String refundedtransactionid)
	{
		getMendixObject().setValue(context, MemberNames.RefundedTransactionId.toString(), refundedtransactionid);
	}

	/**
	 * @return value of RetrievalReferenceNumber
	 */
	public final java.lang.String getRetrievalReferenceNumber()
	{
		return getRetrievalReferenceNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of RetrievalReferenceNumber
	 */
	public final java.lang.String getRetrievalReferenceNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.RetrievalReferenceNumber.toString());
	}

	/**
	 * Set value of RetrievalReferenceNumber
	 * @param retrievalreferencenumber
	 */
	public final void setRetrievalReferenceNumber(java.lang.String retrievalreferencenumber)
	{
		setRetrievalReferenceNumber(getContext(), retrievalreferencenumber);
	}

	/**
	 * Set value of RetrievalReferenceNumber
	 * @param context
	 * @param retrievalreferencenumber
	 */
	public final void setRetrievalReferenceNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String retrievalreferencenumber)
	{
		getMendixObject().setValue(context, MemberNames.RetrievalReferenceNumber.toString(), retrievalreferencenumber);
	}

	/**
	 * @return value of AcquirerReferenceNumber
	 */
	public final java.lang.String getAcquirerReferenceNumber()
	{
		return getAcquirerReferenceNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of AcquirerReferenceNumber
	 */
	public final java.lang.String getAcquirerReferenceNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AcquirerReferenceNumber.toString());
	}

	/**
	 * Set value of AcquirerReferenceNumber
	 * @param acquirerreferencenumber
	 */
	public final void setAcquirerReferenceNumber(java.lang.String acquirerreferencenumber)
	{
		setAcquirerReferenceNumber(getContext(), acquirerreferencenumber);
	}

	/**
	 * Set value of AcquirerReferenceNumber
	 * @param context
	 * @param acquirerreferencenumber
	 */
	public final void setAcquirerReferenceNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String acquirerreferencenumber)
	{
		getMendixObject().setValue(context, MemberNames.AcquirerReferenceNumber.toString(), acquirerreferencenumber);
	}

	/**
	 * @return value of SettlementBatchId
	 */
	public final java.lang.String getSettlementBatchId()
	{
		return getSettlementBatchId(getContext());
	}

	/**
	 * @param context
	 * @return value of SettlementBatchId
	 */
	public final java.lang.String getSettlementBatchId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SettlementBatchId.toString());
	}

	/**
	 * Set value of SettlementBatchId
	 * @param settlementbatchid
	 */
	public final void setSettlementBatchId(java.lang.String settlementbatchid)
	{
		setSettlementBatchId(getContext(), settlementbatchid);
	}

	/**
	 * Set value of SettlementBatchId
	 * @param context
	 * @param settlementbatchid
	 */
	public final void setSettlementBatchId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String settlementbatchid)
	{
		getMendixObject().setValue(context, MemberNames.SettlementBatchId.toString(), settlementbatchid);
	}

	/**
	 * @return value of Status
	 */
	public final java.lang.String getStatus()
	{
		return getStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of Status
	 */
	public final java.lang.String getStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Status.toString());
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final void setStatus(java.lang.String status)
	{
		setStatus(getContext(), status);
	}

	/**
	 * Set value of Status
	 * @param context
	 * @param status
	 */
	public final void setStatus(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String status)
	{
		getMendixObject().setValue(context, MemberNames.Status.toString(), status);
	}

	/**
	 * @return value of SubscriptionId
	 */
	public final java.lang.String getSubscriptionId()
	{
		return getSubscriptionId(getContext());
	}

	/**
	 * @param context
	 * @return value of SubscriptionId
	 */
	public final java.lang.String getSubscriptionId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SubscriptionId.toString());
	}

	/**
	 * Set value of SubscriptionId
	 * @param subscriptionid
	 */
	public final void setSubscriptionId(java.lang.String subscriptionid)
	{
		setSubscriptionId(getContext(), subscriptionid);
	}

	/**
	 * Set value of SubscriptionId
	 * @param context
	 * @param subscriptionid
	 */
	public final void setSubscriptionId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String subscriptionid)
	{
		getMendixObject().setValue(context, MemberNames.SubscriptionId.toString(), subscriptionid);
	}

	/**
	 * @return value of TaxAmount
	 */
	public final java.math.BigDecimal getTaxAmount()
	{
		return getTaxAmount(getContext());
	}

	/**
	 * @param context
	 * @return value of TaxAmount
	 */
	public final java.math.BigDecimal getTaxAmount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.TaxAmount.toString());
	}

	/**
	 * Set value of TaxAmount
	 * @param taxamount
	 */
	public final void setTaxAmount(java.math.BigDecimal taxamount)
	{
		setTaxAmount(getContext(), taxamount);
	}

	/**
	 * Set value of TaxAmount
	 * @param context
	 * @param taxamount
	 */
	public final void setTaxAmount(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal taxamount)
	{
		getMendixObject().setValue(context, MemberNames.TaxAmount.toString(), taxamount);
	}

	/**
	 * @return value of TaxExempt
	 */
	public final java.lang.Boolean getTaxExempt()
	{
		return getTaxExempt(getContext());
	}

	/**
	 * @param context
	 * @return value of TaxExempt
	 */
	public final java.lang.Boolean getTaxExempt(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.TaxExempt.toString());
	}

	/**
	 * Set value of TaxExempt
	 * @param taxexempt
	 */
	public final void setTaxExempt(java.lang.Boolean taxexempt)
	{
		setTaxExempt(getContext(), taxexempt);
	}

	/**
	 * Set value of TaxExempt
	 * @param context
	 * @param taxexempt
	 */
	public final void setTaxExempt(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean taxexempt)
	{
		getMendixObject().setValue(context, MemberNames.TaxExempt.toString(), taxexempt);
	}

	/**
	 * @return value of ShippingAmount
	 */
	public final java.math.BigDecimal getShippingAmount()
	{
		return getShippingAmount(getContext());
	}

	/**
	 * @param context
	 * @return value of ShippingAmount
	 */
	public final java.math.BigDecimal getShippingAmount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.ShippingAmount.toString());
	}

	/**
	 * Set value of ShippingAmount
	 * @param shippingamount
	 */
	public final void setShippingAmount(java.math.BigDecimal shippingamount)
	{
		setShippingAmount(getContext(), shippingamount);
	}

	/**
	 * Set value of ShippingAmount
	 * @param context
	 * @param shippingamount
	 */
	public final void setShippingAmount(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal shippingamount)
	{
		getMendixObject().setValue(context, MemberNames.ShippingAmount.toString(), shippingamount);
	}

	/**
	 * @return value of DiscountAmount
	 */
	public final java.math.BigDecimal getDiscountAmount()
	{
		return getDiscountAmount(getContext());
	}

	/**
	 * @param context
	 * @return value of DiscountAmount
	 */
	public final java.math.BigDecimal getDiscountAmount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.DiscountAmount.toString());
	}

	/**
	 * Set value of DiscountAmount
	 * @param discountamount
	 */
	public final void setDiscountAmount(java.math.BigDecimal discountamount)
	{
		setDiscountAmount(getContext(), discountamount);
	}

	/**
	 * Set value of DiscountAmount
	 * @param context
	 * @param discountamount
	 */
	public final void setDiscountAmount(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal discountamount)
	{
		getMendixObject().setValue(context, MemberNames.DiscountAmount.toString(), discountamount);
	}

	/**
	 * @return value of ShipsFromPostalCode
	 */
	public final java.lang.String getShipsFromPostalCode()
	{
		return getShipsFromPostalCode(getContext());
	}

	/**
	 * @param context
	 * @return value of ShipsFromPostalCode
	 */
	public final java.lang.String getShipsFromPostalCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ShipsFromPostalCode.toString());
	}

	/**
	 * Set value of ShipsFromPostalCode
	 * @param shipsfrompostalcode
	 */
	public final void setShipsFromPostalCode(java.lang.String shipsfrompostalcode)
	{
		setShipsFromPostalCode(getContext(), shipsfrompostalcode);
	}

	/**
	 * Set value of ShipsFromPostalCode
	 * @param context
	 * @param shipsfrompostalcode
	 */
	public final void setShipsFromPostalCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String shipsfrompostalcode)
	{
		getMendixObject().setValue(context, MemberNames.ShipsFromPostalCode.toString(), shipsfrompostalcode);
	}

	/**
	 * @return value of _type
	 */
	public final java.lang.String get_type()
	{
		return get_type(getContext());
	}

	/**
	 * @param context
	 * @return value of _type
	 */
	public final java.lang.String get_type(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._type.toString());
	}

	/**
	 * Set value of _type
	 * @param _type
	 */
	public final void set_type(java.lang.String _type)
	{
		set_type(getContext(), _type);
	}

	/**
	 * Set value of _type
	 * @param context
	 * @param _type
	 */
	public final void set_type(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _type)
	{
		getMendixObject().setValue(context, MemberNames._type.toString(), _type);
	}

	/**
	 * @return value of UpdatedAt
	 */
	public final java.lang.Long getUpdatedAt()
	{
		return getUpdatedAt(getContext());
	}

	/**
	 * @param context
	 * @return value of UpdatedAt
	 */
	public final java.lang.Long getUpdatedAt(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.UpdatedAt.toString());
	}

	/**
	 * Set value of UpdatedAt
	 * @param updatedat
	 */
	public final void setUpdatedAt(java.lang.Long updatedat)
	{
		setUpdatedAt(getContext(), updatedat);
	}

	/**
	 * Set value of UpdatedAt
	 * @param context
	 * @param updatedat
	 */
	public final void setUpdatedAt(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long updatedat)
	{
		getMendixObject().setValue(context, MemberNames.UpdatedAt.toString(), updatedat);
	}

	/**
	 * @return value of ServiceFeeAmount
	 */
	public final java.math.BigDecimal getServiceFeeAmount()
	{
		return getServiceFeeAmount(getContext());
	}

	/**
	 * @param context
	 * @return value of ServiceFeeAmount
	 */
	public final java.math.BigDecimal getServiceFeeAmount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.ServiceFeeAmount.toString());
	}

	/**
	 * Set value of ServiceFeeAmount
	 * @param servicefeeamount
	 */
	public final void setServiceFeeAmount(java.math.BigDecimal servicefeeamount)
	{
		setServiceFeeAmount(getContext(), servicefeeamount);
	}

	/**
	 * Set value of ServiceFeeAmount
	 * @param context
	 * @param servicefeeamount
	 */
	public final void setServiceFeeAmount(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal servicefeeamount)
	{
		getMendixObject().setValue(context, MemberNames.ServiceFeeAmount.toString(), servicefeeamount);
	}

	/**
	 * @return value of PaymentInstrumentType
	 */
	public final java.lang.String getPaymentInstrumentType()
	{
		return getPaymentInstrumentType(getContext());
	}

	/**
	 * @param context
	 * @return value of PaymentInstrumentType
	 */
	public final java.lang.String getPaymentInstrumentType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PaymentInstrumentType.toString());
	}

	/**
	 * Set value of PaymentInstrumentType
	 * @param paymentinstrumenttype
	 */
	public final void setPaymentInstrumentType(java.lang.String paymentinstrumenttype)
	{
		setPaymentInstrumentType(getContext(), paymentinstrumenttype);
	}

	/**
	 * Set value of PaymentInstrumentType
	 * @param context
	 * @param paymentinstrumenttype
	 */
	public final void setPaymentInstrumentType(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String paymentinstrumenttype)
	{
		getMendixObject().setValue(context, MemberNames.PaymentInstrumentType.toString(), paymentinstrumenttype);
	}

	/**
	 * @return value of AuthorizedTransactionId
	 */
	public final java.lang.String getAuthorizedTransactionId()
	{
		return getAuthorizedTransactionId(getContext());
	}

	/**
	 * @param context
	 * @return value of AuthorizedTransactionId
	 */
	public final java.lang.String getAuthorizedTransactionId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AuthorizedTransactionId.toString());
	}

	/**
	 * Set value of AuthorizedTransactionId
	 * @param authorizedtransactionid
	 */
	public final void setAuthorizedTransactionId(java.lang.String authorizedtransactionid)
	{
		setAuthorizedTransactionId(getContext(), authorizedtransactionid);
	}

	/**
	 * Set value of AuthorizedTransactionId
	 * @param context
	 * @param authorizedtransactionid
	 */
	public final void setAuthorizedTransactionId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String authorizedtransactionid)
	{
		getMendixObject().setValue(context, MemberNames.AuthorizedTransactionId.toString(), authorizedtransactionid);
	}

	/**
	 * @return value of NetworkTransactionId
	 */
	public final java.lang.String getNetworkTransactionId()
	{
		return getNetworkTransactionId(getContext());
	}

	/**
	 * @param context
	 * @return value of NetworkTransactionId
	 */
	public final java.lang.String getNetworkTransactionId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.NetworkTransactionId.toString());
	}

	/**
	 * Set value of NetworkTransactionId
	 * @param networktransactionid
	 */
	public final void setNetworkTransactionId(java.lang.String networktransactionid)
	{
		setNetworkTransactionId(getContext(), networktransactionid);
	}

	/**
	 * Set value of NetworkTransactionId
	 * @param context
	 * @param networktransactionid
	 */
	public final void setNetworkTransactionId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String networktransactionid)
	{
		getMendixObject().setValue(context, MemberNames.NetworkTransactionId.toString(), networktransactionid);
	}

	/**
	 * @return value of ScaExemptionRequested
	 */
	public final java.lang.String getScaExemptionRequested()
	{
		return getScaExemptionRequested(getContext());
	}

	/**
	 * @param context
	 * @return value of ScaExemptionRequested
	 */
	public final java.lang.String getScaExemptionRequested(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ScaExemptionRequested.toString());
	}

	/**
	 * Set value of ScaExemptionRequested
	 * @param scaexemptionrequested
	 */
	public final void setScaExemptionRequested(java.lang.String scaexemptionrequested)
	{
		setScaExemptionRequested(getContext(), scaexemptionrequested);
	}

	/**
	 * Set value of ScaExemptionRequested
	 * @param context
	 * @param scaexemptionrequested
	 */
	public final void setScaExemptionRequested(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String scaexemptionrequested)
	{
		getMendixObject().setValue(context, MemberNames.ScaExemptionRequested.toString(), scaexemptionrequested);
	}

	/**
	 * @return value of AuthorizationExpiresAt
	 */
	public final java.lang.Long getAuthorizationExpiresAt()
	{
		return getAuthorizationExpiresAt(getContext());
	}

	/**
	 * @param context
	 * @return value of AuthorizationExpiresAt
	 */
	public final java.lang.Long getAuthorizationExpiresAt(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.AuthorizationExpiresAt.toString());
	}

	/**
	 * Set value of AuthorizationExpiresAt
	 * @param authorizationexpiresat
	 */
	public final void setAuthorizationExpiresAt(java.lang.Long authorizationexpiresat)
	{
		setAuthorizationExpiresAt(getContext(), authorizationexpiresat);
	}

	/**
	 * Set value of AuthorizationExpiresAt
	 * @param context
	 * @param authorizationexpiresat
	 */
	public final void setAuthorizationExpiresAt(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long authorizationexpiresat)
	{
		getMendixObject().setValue(context, MemberNames.AuthorizationExpiresAt.toString(), authorizationexpiresat);
	}

	/**
	 * @return value of InstallmentCount
	 */
	public final java.lang.Integer getInstallmentCount()
	{
		return getInstallmentCount(getContext());
	}

	/**
	 * @param context
	 * @return value of InstallmentCount
	 */
	public final java.lang.Integer getInstallmentCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.InstallmentCount.toString());
	}

	/**
	 * Set value of InstallmentCount
	 * @param installmentcount
	 */
	public final void setInstallmentCount(java.lang.Integer installmentcount)
	{
		setInstallmentCount(getContext(), installmentcount);
	}

	/**
	 * Set value of InstallmentCount
	 * @param context
	 * @param installmentcount
	 */
	public final void setInstallmentCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer installmentcount)
	{
		getMendixObject().setValue(context, MemberNames.InstallmentCount.toString(), installmentcount);
	}

	/**
	 * @return value of Disbursed
	 */
	public final java.lang.Boolean getDisbursed()
	{
		return getDisbursed(getContext());
	}

	/**
	 * @param context
	 * @return value of Disbursed
	 */
	public final java.lang.Boolean getDisbursed(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Disbursed.toString());
	}

	/**
	 * Set value of Disbursed
	 * @param disbursed
	 */
	public final void setDisbursed(java.lang.Boolean disbursed)
	{
		setDisbursed(getContext(), disbursed);
	}

	/**
	 * Set value of Disbursed
	 * @param context
	 * @param disbursed
	 */
	public final void setDisbursed(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean disbursed)
	{
		getMendixObject().setValue(context, MemberNames.Disbursed.toString(), disbursed);
	}

	/**
	 * @return value of GraphQLId
	 */
	public final java.lang.String getGraphQLId()
	{
		return getGraphQLId(getContext());
	}

	/**
	 * @param context
	 * @return value of GraphQLId
	 */
	public final java.lang.String getGraphQLId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.GraphQLId.toString());
	}

	/**
	 * Set value of GraphQLId
	 * @param graphqlid
	 */
	public final void setGraphQLId(java.lang.String graphqlid)
	{
		setGraphQLId(getContext(), graphqlid);
	}

	/**
	 * Set value of GraphQLId
	 * @param context
	 * @param graphqlid
	 */
	public final void setGraphQLId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String graphqlid)
	{
		getMendixObject().setValue(context, MemberNames.GraphQLId.toString(), graphqlid);
	}

	/**
	 * @return value of BillingAddress_Transaction
	 */
	public final braintreegateway.proxies.BillingAddress getBillingAddress_Transaction() throws com.mendix.core.CoreException
	{
		return getBillingAddress_Transaction(getContext());
	}

	/**
	 * @param context
	 * @return value of BillingAddress_Transaction
	 */
	public final braintreegateway.proxies.BillingAddress getBillingAddress_Transaction(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		braintreegateway.proxies.BillingAddress result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.BillingAddress_Transaction.toString());
		if (identifier != null)
			result = braintreegateway.proxies.BillingAddress.load(context, identifier);
		return result;
	}

	/**
	 * Set value of BillingAddress_Transaction
	 * @param billingaddress_transaction
	 */
	public final void setBillingAddress_Transaction(braintreegateway.proxies.BillingAddress billingaddress_transaction)
	{
		setBillingAddress_Transaction(getContext(), billingaddress_transaction);
	}

	/**
	 * Set value of BillingAddress_Transaction
	 * @param context
	 * @param billingaddress_transaction
	 */
	public final void setBillingAddress_Transaction(com.mendix.systemwideinterfaces.core.IContext context, braintreegateway.proxies.BillingAddress billingaddress_transaction)
	{
		if (billingaddress_transaction == null)
			getMendixObject().setValue(context, MemberNames.BillingAddress_Transaction.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.BillingAddress_Transaction.toString(), billingaddress_transaction.getMendixObject().getId());
	}

	/**
	 * @return value of CreditCard_Transaction
	 */
	public final braintreegateway.proxies.CreditCard getCreditCard_Transaction() throws com.mendix.core.CoreException
	{
		return getCreditCard_Transaction(getContext());
	}

	/**
	 * @param context
	 * @return value of CreditCard_Transaction
	 */
	public final braintreegateway.proxies.CreditCard getCreditCard_Transaction(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		braintreegateway.proxies.CreditCard result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.CreditCard_Transaction.toString());
		if (identifier != null)
			result = braintreegateway.proxies.CreditCard.load(context, identifier);
		return result;
	}

	/**
	 * Set value of CreditCard_Transaction
	 * @param creditcard_transaction
	 */
	public final void setCreditCard_Transaction(braintreegateway.proxies.CreditCard creditcard_transaction)
	{
		setCreditCard_Transaction(getContext(), creditcard_transaction);
	}

	/**
	 * Set value of CreditCard_Transaction
	 * @param context
	 * @param creditcard_transaction
	 */
	public final void setCreditCard_Transaction(com.mendix.systemwideinterfaces.core.IContext context, braintreegateway.proxies.CreditCard creditcard_transaction)
	{
		if (creditcard_transaction == null)
			getMendixObject().setValue(context, MemberNames.CreditCard_Transaction.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.CreditCard_Transaction.toString(), creditcard_transaction.getMendixObject().getId());
	}

	/**
	 * @return value of DisbursementDetails_Transaction
	 */
	public final braintreegateway.proxies.DisbursementDetails getDisbursementDetails_Transaction() throws com.mendix.core.CoreException
	{
		return getDisbursementDetails_Transaction(getContext());
	}

	/**
	 * @param context
	 * @return value of DisbursementDetails_Transaction
	 */
	public final braintreegateway.proxies.DisbursementDetails getDisbursementDetails_Transaction(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		braintreegateway.proxies.DisbursementDetails result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DisbursementDetails_Transaction.toString());
		if (identifier != null)
			result = braintreegateway.proxies.DisbursementDetails.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DisbursementDetails_Transaction
	 * @param disbursementdetails_transaction
	 */
	public final void setDisbursementDetails_Transaction(braintreegateway.proxies.DisbursementDetails disbursementdetails_transaction)
	{
		setDisbursementDetails_Transaction(getContext(), disbursementdetails_transaction);
	}

	/**
	 * Set value of DisbursementDetails_Transaction
	 * @param context
	 * @param disbursementdetails_transaction
	 */
	public final void setDisbursementDetails_Transaction(com.mendix.systemwideinterfaces.core.IContext context, braintreegateway.proxies.DisbursementDetails disbursementdetails_transaction)
	{
		if (disbursementdetails_transaction == null)
			getMendixObject().setValue(context, MemberNames.DisbursementDetails_Transaction.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DisbursementDetails_Transaction.toString(), disbursementdetails_transaction.getMendixObject().getId());
	}

	/**
	 * @return value of Descriptor_Transaction
	 */
	public final braintreegateway.proxies.Descriptor getDescriptor_Transaction() throws com.mendix.core.CoreException
	{
		return getDescriptor_Transaction(getContext());
	}

	/**
	 * @param context
	 * @return value of Descriptor_Transaction
	 */
	public final braintreegateway.proxies.Descriptor getDescriptor_Transaction(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		braintreegateway.proxies.Descriptor result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Descriptor_Transaction.toString());
		if (identifier != null)
			result = braintreegateway.proxies.Descriptor.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Descriptor_Transaction
	 * @param descriptor_transaction
	 */
	public final void setDescriptor_Transaction(braintreegateway.proxies.Descriptor descriptor_transaction)
	{
		setDescriptor_Transaction(getContext(), descriptor_transaction);
	}

	/**
	 * Set value of Descriptor_Transaction
	 * @param context
	 * @param descriptor_transaction
	 */
	public final void setDescriptor_Transaction(com.mendix.systemwideinterfaces.core.IContext context, braintreegateway.proxies.Descriptor descriptor_transaction)
	{
		if (descriptor_transaction == null)
			getMendixObject().setValue(context, MemberNames.Descriptor_Transaction.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Descriptor_Transaction.toString(), descriptor_transaction.getMendixObject().getId());
	}

	/**
	 * @return value of ApplePayDetails_Transaction
	 */
	public final braintreegateway.proxies.ApplePayDetails getApplePayDetails_Transaction() throws com.mendix.core.CoreException
	{
		return getApplePayDetails_Transaction(getContext());
	}

	/**
	 * @param context
	 * @return value of ApplePayDetails_Transaction
	 */
	public final braintreegateway.proxies.ApplePayDetails getApplePayDetails_Transaction(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		braintreegateway.proxies.ApplePayDetails result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ApplePayDetails_Transaction.toString());
		if (identifier != null)
			result = braintreegateway.proxies.ApplePayDetails.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ApplePayDetails_Transaction
	 * @param applepaydetails_transaction
	 */
	public final void setApplePayDetails_Transaction(braintreegateway.proxies.ApplePayDetails applepaydetails_transaction)
	{
		setApplePayDetails_Transaction(getContext(), applepaydetails_transaction);
	}

	/**
	 * Set value of ApplePayDetails_Transaction
	 * @param context
	 * @param applepaydetails_transaction
	 */
	public final void setApplePayDetails_Transaction(com.mendix.systemwideinterfaces.core.IContext context, braintreegateway.proxies.ApplePayDetails applepaydetails_transaction)
	{
		if (applepaydetails_transaction == null)
			getMendixObject().setValue(context, MemberNames.ApplePayDetails_Transaction.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ApplePayDetails_Transaction.toString(), applepaydetails_transaction.getMendixObject().getId());
	}

	/**
	 * @return value of AndroidPayDetails_Transaction
	 */
	public final braintreegateway.proxies.AndroidPayDetails getAndroidPayDetails_Transaction() throws com.mendix.core.CoreException
	{
		return getAndroidPayDetails_Transaction(getContext());
	}

	/**
	 * @param context
	 * @return value of AndroidPayDetails_Transaction
	 */
	public final braintreegateway.proxies.AndroidPayDetails getAndroidPayDetails_Transaction(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		braintreegateway.proxies.AndroidPayDetails result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.AndroidPayDetails_Transaction.toString());
		if (identifier != null)
			result = braintreegateway.proxies.AndroidPayDetails.load(context, identifier);
		return result;
	}

	/**
	 * Set value of AndroidPayDetails_Transaction
	 * @param androidpaydetails_transaction
	 */
	public final void setAndroidPayDetails_Transaction(braintreegateway.proxies.AndroidPayDetails androidpaydetails_transaction)
	{
		setAndroidPayDetails_Transaction(getContext(), androidpaydetails_transaction);
	}

	/**
	 * Set value of AndroidPayDetails_Transaction
	 * @param context
	 * @param androidpaydetails_transaction
	 */
	public final void setAndroidPayDetails_Transaction(com.mendix.systemwideinterfaces.core.IContext context, braintreegateway.proxies.AndroidPayDetails androidpaydetails_transaction)
	{
		if (androidpaydetails_transaction == null)
			getMendixObject().setValue(context, MemberNames.AndroidPayDetails_Transaction.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.AndroidPayDetails_Transaction.toString(), androidpaydetails_transaction.getMendixObject().getId());
	}

	/**
	 * @return value of ShippingAddress_Transaction
	 */
	public final braintreegateway.proxies.ShippingAddress getShippingAddress_Transaction() throws com.mendix.core.CoreException
	{
		return getShippingAddress_Transaction(getContext());
	}

	/**
	 * @param context
	 * @return value of ShippingAddress_Transaction
	 */
	public final braintreegateway.proxies.ShippingAddress getShippingAddress_Transaction(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		braintreegateway.proxies.ShippingAddress result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ShippingAddress_Transaction.toString());
		if (identifier != null)
			result = braintreegateway.proxies.ShippingAddress.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ShippingAddress_Transaction
	 * @param shippingaddress_transaction
	 */
	public final void setShippingAddress_Transaction(braintreegateway.proxies.ShippingAddress shippingaddress_transaction)
	{
		setShippingAddress_Transaction(getContext(), shippingaddress_transaction);
	}

	/**
	 * Set value of ShippingAddress_Transaction
	 * @param context
	 * @param shippingaddress_transaction
	 */
	public final void setShippingAddress_Transaction(com.mendix.systemwideinterfaces.core.IContext context, braintreegateway.proxies.ShippingAddress shippingaddress_transaction)
	{
		if (shippingaddress_transaction == null)
			getMendixObject().setValue(context, MemberNames.ShippingAddress_Transaction.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ShippingAddress_Transaction.toString(), shippingaddress_transaction.getMendixObject().getId());
	}

	/**
	 * @return value of SubscriptionDetails_Transaction
	 */
	public final braintreegateway.proxies.SubscriptionDetails getSubscriptionDetails_Transaction() throws com.mendix.core.CoreException
	{
		return getSubscriptionDetails_Transaction(getContext());
	}

	/**
	 * @param context
	 * @return value of SubscriptionDetails_Transaction
	 */
	public final braintreegateway.proxies.SubscriptionDetails getSubscriptionDetails_Transaction(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		braintreegateway.proxies.SubscriptionDetails result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SubscriptionDetails_Transaction.toString());
		if (identifier != null)
			result = braintreegateway.proxies.SubscriptionDetails.load(context, identifier);
		return result;
	}

	/**
	 * Set value of SubscriptionDetails_Transaction
	 * @param subscriptiondetails_transaction
	 */
	public final void setSubscriptionDetails_Transaction(braintreegateway.proxies.SubscriptionDetails subscriptiondetails_transaction)
	{
		setSubscriptionDetails_Transaction(getContext(), subscriptiondetails_transaction);
	}

	/**
	 * Set value of SubscriptionDetails_Transaction
	 * @param context
	 * @param subscriptiondetails_transaction
	 */
	public final void setSubscriptionDetails_Transaction(com.mendix.systemwideinterfaces.core.IContext context, braintreegateway.proxies.SubscriptionDetails subscriptiondetails_transaction)
	{
		if (subscriptiondetails_transaction == null)
			getMendixObject().setValue(context, MemberNames.SubscriptionDetails_Transaction.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.SubscriptionDetails_Transaction.toString(), subscriptiondetails_transaction.getMendixObject().getId());
	}

	/**
	 * @return value of RiskData_Transaction
	 */
	public final braintreegateway.proxies.RiskData getRiskData_Transaction() throws com.mendix.core.CoreException
	{
		return getRiskData_Transaction(getContext());
	}

	/**
	 * @param context
	 * @return value of RiskData_Transaction
	 */
	public final braintreegateway.proxies.RiskData getRiskData_Transaction(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		braintreegateway.proxies.RiskData result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.RiskData_Transaction.toString());
		if (identifier != null)
			result = braintreegateway.proxies.RiskData.load(context, identifier);
		return result;
	}

	/**
	 * Set value of RiskData_Transaction
	 * @param riskdata_transaction
	 */
	public final void setRiskData_Transaction(braintreegateway.proxies.RiskData riskdata_transaction)
	{
		setRiskData_Transaction(getContext(), riskdata_transaction);
	}

	/**
	 * Set value of RiskData_Transaction
	 * @param context
	 * @param riskdata_transaction
	 */
	public final void setRiskData_Transaction(com.mendix.systemwideinterfaces.core.IContext context, braintreegateway.proxies.RiskData riskdata_transaction)
	{
		if (riskdata_transaction == null)
			getMendixObject().setValue(context, MemberNames.RiskData_Transaction.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.RiskData_Transaction.toString(), riskdata_transaction.getMendixObject().getId());
	}

	/**
	 * @return value of PayPalDetails_Transaction
	 */
	public final braintreegateway.proxies.PayPalDetails getPayPalDetails_Transaction() throws com.mendix.core.CoreException
	{
		return getPayPalDetails_Transaction(getContext());
	}

	/**
	 * @param context
	 * @return value of PayPalDetails_Transaction
	 */
	public final braintreegateway.proxies.PayPalDetails getPayPalDetails_Transaction(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		braintreegateway.proxies.PayPalDetails result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.PayPalDetails_Transaction.toString());
		if (identifier != null)
			result = braintreegateway.proxies.PayPalDetails.load(context, identifier);
		return result;
	}

	/**
	 * Set value of PayPalDetails_Transaction
	 * @param paypaldetails_transaction
	 */
	public final void setPayPalDetails_Transaction(braintreegateway.proxies.PayPalDetails paypaldetails_transaction)
	{
		setPayPalDetails_Transaction(getContext(), paypaldetails_transaction);
	}

	/**
	 * Set value of PayPalDetails_Transaction
	 * @param context
	 * @param paypaldetails_transaction
	 */
	public final void setPayPalDetails_Transaction(com.mendix.systemwideinterfaces.core.IContext context, braintreegateway.proxies.PayPalDetails paypaldetails_transaction)
	{
		if (paypaldetails_transaction == null)
			getMendixObject().setValue(context, MemberNames.PayPalDetails_Transaction.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.PayPalDetails_Transaction.toString(), paypaldetails_transaction.getMendixObject().getId());
	}

	/**
	 * @return value of ThreeDSecureInfo_Transaction
	 */
	public final braintreegateway.proxies.ThreeDSecureInfo getThreeDSecureInfo_Transaction() throws com.mendix.core.CoreException
	{
		return getThreeDSecureInfo_Transaction(getContext());
	}

	/**
	 * @param context
	 * @return value of ThreeDSecureInfo_Transaction
	 */
	public final braintreegateway.proxies.ThreeDSecureInfo getThreeDSecureInfo_Transaction(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		braintreegateway.proxies.ThreeDSecureInfo result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ThreeDSecureInfo_Transaction.toString());
		if (identifier != null)
			result = braintreegateway.proxies.ThreeDSecureInfo.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ThreeDSecureInfo_Transaction
	 * @param threedsecureinfo_transaction
	 */
	public final void setThreeDSecureInfo_Transaction(braintreegateway.proxies.ThreeDSecureInfo threedsecureinfo_transaction)
	{
		setThreeDSecureInfo_Transaction(getContext(), threedsecureinfo_transaction);
	}

	/**
	 * Set value of ThreeDSecureInfo_Transaction
	 * @param context
	 * @param threedsecureinfo_transaction
	 */
	public final void setThreeDSecureInfo_Transaction(com.mendix.systemwideinterfaces.core.IContext context, braintreegateway.proxies.ThreeDSecureInfo threedsecureinfo_transaction)
	{
		if (threedsecureinfo_transaction == null)
			getMendixObject().setValue(context, MemberNames.ThreeDSecureInfo_Transaction.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ThreeDSecureInfo_Transaction.toString(), threedsecureinfo_transaction.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return transactionMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final braintreegateway.proxies.Transaction that = (braintreegateway.proxies.Transaction) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "BraintreeGateway.Transaction";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
