// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testing.proxies;

public class Configuration
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject configurationMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Testing.Configuration";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ShopName("ShopName"),
		TotalLabel("TotalLabel");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Configuration(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Testing.Configuration"));
	}

	protected Configuration(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject configurationMendixObject)
	{
		if (configurationMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Testing.Configuration", configurationMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Testing.Configuration");

		this.configurationMendixObject = configurationMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Configuration.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static testing.proxies.Configuration initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return testing.proxies.Configuration.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static testing.proxies.Configuration initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new testing.proxies.Configuration(context, mendixObject);
	}

	public static testing.proxies.Configuration load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return testing.proxies.Configuration.initialize(context, mendixObject);
	}

	public static java.util.List<testing.proxies.Configuration> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<testing.proxies.Configuration> result = new java.util.ArrayList<testing.proxies.Configuration>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Testing.Configuration" + xpathConstraint))
			result.add(testing.proxies.Configuration.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of ShopName
	 */
	public final java.lang.String getShopName()
	{
		return getShopName(getContext());
	}

	/**
	 * @param context
	 * @return value of ShopName
	 */
	public final java.lang.String getShopName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ShopName.toString());
	}

	/**
	 * Set value of ShopName
	 * @param shopname
	 */
	public final void setShopName(java.lang.String shopname)
	{
		setShopName(getContext(), shopname);
	}

	/**
	 * Set value of ShopName
	 * @param context
	 * @param shopname
	 */
	public final void setShopName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String shopname)
	{
		getMendixObject().setValue(context, MemberNames.ShopName.toString(), shopname);
	}

	/**
	 * @return value of TotalLabel
	 */
	public final java.lang.String getTotalLabel()
	{
		return getTotalLabel(getContext());
	}

	/**
	 * @param context
	 * @return value of TotalLabel
	 */
	public final java.lang.String getTotalLabel(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TotalLabel.toString());
	}

	/**
	 * Set value of TotalLabel
	 * @param totallabel
	 */
	public final void setTotalLabel(java.lang.String totallabel)
	{
		setTotalLabel(getContext(), totallabel);
	}

	/**
	 * Set value of TotalLabel
	 * @param context
	 * @param totallabel
	 */
	public final void setTotalLabel(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String totallabel)
	{
		getMendixObject().setValue(context, MemberNames.TotalLabel.toString(), totallabel);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return configurationMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final testing.proxies.Configuration that = (testing.proxies.Configuration) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Testing.Configuration";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
