// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package braintreegateway.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	// These are the microflows for the BraintreeGateway module
	public static void sUB_GenerateClientToken(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("BraintreeGateway.SUB_GenerateClientToken").withParams(params).execute(context);
	}
	public static void sUB_Initialise(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("BraintreeGateway.SUB_Initialise").withParams(params).execute(context);
	}
	public static void sUB_ProcessPayment(IContext context, braintreegateway.proxies.Client _client)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Client", _client == null ? null : _client.getMendixObject());
		Core.microflowCall("BraintreeGateway.SUB_ProcessPayment").withParams(params).execute(context);
	}
}