// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package braintreegateway.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import braintreegateway.actions.tools.Payment;

/**
 * Will generate a client token for the Drop-in widget to use.
 */
public class GenerateClientToken extends CustomJavaAction<java.lang.String>
{
	private java.lang.String OptionalCustomerID;

	public GenerateClientToken(IContext context, java.lang.String OptionalCustomerID)
	{
		super(context);
		this.OptionalCustomerID = OptionalCustomerID;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		if (this.OptionalCustomerID != null) return Payment.generateClientToken(this.OptionalCustomerID);
		else return Payment.generateClientToken();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GenerateClientToken";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
