// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testing.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	// These are the microflows for the Testing module
	public static void aCT_2_CapturePaymentDetails(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Testing.ACT_2_CapturePaymentDetails").withParams(params).execute(context);
	}
	public static void aCT_3_ConfirmTransaction(IContext context, braintreegateway.proxies.Client _client)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Client", _client == null ? null : _client.getMendixObject());
		Core.microflowCall("Testing.ACT_3_ConfirmTransaction").withParams(params).execute(context);
	}
	public static boolean aS_1_CreateBraintree(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		return (java.lang.Boolean) Core.microflowCall("Testing.AS_1_CreateBraintree").withParams(params).execute(context);
	}
}